### ISSUE TITLE
device doesnt go on sleep mode

### ISSUE THREAD

**Issue by razzbee** [kivy/python-for-android#969] opened 2016-12-26 00:56 UTC
Hello I have successfully compiled and installed my kivy app on android 6 device , but the device doesnt  go on sleep mode even though I havent enabled wake lock

I am using the master branch of kivy , python for android and buildozer. Thank you

**Comment by KeyWeeUsr** [comment] 2016-12-26 00:59
Are you sure you haven't enabled it in `Developer settings` or in a similar OS settings? Don't you have it connected via USB or something? The basic app isn't able to make Android stay awake.

**Comment by razzbee** [comment] 2016-12-26 01:11
the same happens even with usb attached , besides I havent enabled 'Stay Awake' mode in developers settings (Off)

**Comment by KeyWeeUsr** [comment] 2016-12-26 01:22
Can you provide the APK and/or the code?

**Comment by razzbee** [comment] 2016-12-26 01:23
let me send apk , do I upload it here?

**Comment by razzbee** [comment] 2016-12-26 01:35
App Uploaded here : http://playslack.com/MediaMate-0.1-debug.apk

**Comment by razzbee** [comment] 2016-12-26 01:58
I have opensourced the core part (as planned ) docs is not very good , but that should at least help. https://github.com/razzbee/kivy-android-webview

**Comment by razzbee** [comment] 2016-12-26 10:23
any solution yet?

**Comment by KeyWeeUsr** [comment] 2016-12-26 10:44
The apk seems corrupted for some reason, can't open it on both phone or pc. However, the code doesn't seem to have any issues with the lock itself. Have you tried it on some other device with higher/lower/same android version? Apparently if the apk is really corrupted, you'll need to paste here the `AndroidManifest.xml` file.

I still think it's something enabled on your device that forbids the phone to sleep.

**Comment by razzbee** [comment] 2016-12-26 11:35
I have reuploaded the apk , http://playslack.com/mediamate.apk , again the app crashes for android version less than 4.4

**Comment by KeyWeeUsr** [comment] 2016-12-26 11:54
Confirmed, yet I have no clue why. App doesn't use any related permission to wake lock (check manifest), I have no such option enabled and even the code seems to be correct. Webview bootstrap [too](https://github.com/kivy/python-for-android/blob/ef9e75bbdd6f626da01e9d153e967ebdc89b1482/pythonforandroid/bootstraps/webview/build/src/org/kivy/android/PythonActivity.java#L172).

Android 4.4.2

**Comment by razzbee** [comment] 2016-12-26 12:04
okay , but about this launch crash on android < 4.4 , is there any solution to that?

**Comment by KeyWeeUsr** [comment] 2016-12-26 12:17
Lowering minimal api for your app, otherwise I don't know. Logcat would be needed for the crash.

**Comment by razzbee** [comment] 2016-12-27 14:37
I think te non sleep mode is not from my code , because I tried compiling hello world and had the same bug, tried on android 5 & 6 devices

**Comment by razzbee** [comment] 2016-12-27 16:58
Well I figured out that this error happens with the sdl2 backend , pygame backend doesnt have this bug

**Comment by KeyWeeUsr** [comment] 2016-12-27 18:35
@inclement I tested it with both pygame and sdl2 launchers + that `testapp_setup`:
* neither of launchers have this bug in project chooser screen
* pygame after app launch sleeps well
* sdl2 doesn't sleep
* testapp doesn't sleep

any idea why? Webview isn't build upon sdl2, is it?

**Comment by razzbee** [comment] 2016-12-28 04:02
I cant use the pygame bootstrap , app crashes randomly with the pygame bootstrap , Please is there a fix for sdl2 bootstrap??

**Comment by razzbee** [comment] 2016-12-28 22:17
@inclement , @tito **PLEASE** can you investigate into this since its not only webview apps, any app I compile using the sdl2 backend prevent device from entering **sleep mode**

**Comment by FeralBytes** [comment] 2016-12-29 01:20
@razzbee, why not just have your program stop after a set amount of time? Then the device will do it's normal sleep routine. Also if you want the device to sleep and still want to do things then you should make a service. If you service has forefront priority with a icon in the menu you can also get rid of that using some pyjinus; I put some code for that into the wiki.

**Comment by razzbee** [comment] 2016-12-29 01:34
I have posted a sample demo , you can test it, besides , have you tried the new toolchain with sdl bootstrap (using buildozer) : http://playslack.com/mediamate.apk

**Comment by inclement** [comment] 2017-01-08 00:28
I've checked the wakelock defaults, but it does default to 0 as it should. I guess this depends on something slightly different, and I'll keep looking into it.

**Comment by inclement** [comment] 2017-01-08 00:31
Perhaps https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/sdl2/build/src/org/libsdl/app/SDLActivity.java#L371 is the culprit.

**Comment by inclement** [comment] 2017-01-08 00:39
It looks like this is the Android manifestation of SDL2's screensaver suspension by default, as described [here](https://wiki.libsdl.org/FAQUsingSDL#Why_does_SDL_disable_my_screensaver_by_default.3F). You can try setting the env var as explained there as a temporary workaround. I'll look at a proper fix sometime soonish.

**Comment by razzbee** [comment] 2017-01-13 17:33
This might be a silly question to ask but any idea on how to set the ENV variable in my code ???

**Comment by inclement** [comment] 2017-01-13 18:12
I was thinking it would be sufficient to add `from os import environ; environ['SDL_VIDEO_ALLOW_SCREENSAVER']` at the top of your python file (before any other imports). On reflection I'm not sure if that is early enough, but it should be okay.

**Comment by razzbee** [comment] 2017-01-13 18:54
Thank you, I will try it and give you the feedback

**Comment by inclement** [comment] 2017-01-14 22:26
I've just checked this myself, and adding this env var does allow the device to sleep properly. I'm looking at how this should be fixed fully in Kivy.

**Closed** 2017-02-02 11:28 UTC
