### ISSUE TITLE
static jfieldID xxx not valid for class java.lang.Class<org.renpy.android.PythonActivity

### ISSUE THREAD

**Issue by xxnet** [kivy/python-for-android#696] opened 2016-03-30 02:22 UTC
The build out apk run correctly on Android 4.x， but fail on Android 5.1.1 and Android 6

log is same as:
https://github.com/kivy/python-for-android/issues/686

What is the problem and how to solve this?
how to figure it out?

Thanks.
##

**Comment by inclement** [comment] 2016-04-03 16:34
According to the linked issue, this is to do with accessing attributes of org.renpy.android.PythonActivity with the SDL2 bootstrap, in which case this is only a shim and you should instead use org.kivy.android.PythonActivity. Is that what you're asking about?

**Comment by xxnet** [comment] 2016-04-05 07:29
It triggered at https://kivy.org/docs/_modules/kivy/metrics.html

> @reify
>    def fontscale(self):
>        '''Return the fontscale user preference. This value is 1 by default but
>        can vary between 0.8 and 1.2.
>        '''
>        custom_fontscale = environ.get('KIVY_METRICS_FONTSCALE')
>        if custom_fontscale:
>            return float(custom_fontscale)
>
>        if platform == 'android':
>            from jnius import autoclass
>            if USE_SDL2:
>                PythonActivity = autoclass('org.kivy.android.PythonActivity')
>            else:
>                PythonActivity = autoclass('org.renpy.android.PythonActivity')
>            config = PythonActivity.mActivity.getResources().getConfiguration()
>            return config.fontScale

I change bootstrap to pygame to avoid this but not work stable.
Maybe some bug there.

**Comment by inclement** [comment] 2019-01-30 22:38
Closing as not a bug.

**Closed by inclement** 2019-01-30 22:38 UTC
