### ISSUE TITLE
App close when device is flipped

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/python-for-android#732] opened 2016-05-06 02:21 UTC
```
05-06 04:00:06.523 9423-9443/? I/python: [INFO              ] [Android     ] Must go into sleep mode, check the app
05-06 04:00:06.523 9423-9443/? I/python: [INFO              ] [Android     ] App paused, now wait for resume.
05-06 04:00:06.533 9423-9443/? I/python: [INFO              ] [Android     ] Android wants to close our app.
05-06 04:00:06.543 9423-9443/? I/python: [INFO              ] [Base        ] Leaving application in progress...
05-06 04:00:06.953 9423-9443/? I/python: Python for android ended.
05-06 04:00:06.983 793-1738/? I/ActivityManager: Process pytbepygame.test.pytbepygame:python (pid 9423) (adj 0) has died.
05-06 04:00:06.983 793-1737/? I/WindowState: WIN DEATH: Window{4215d150 u0 pytbepygame.test.pytbepygame/org.renpy.android.PythonActivity}
05-06 04:00:06.983 793-1737/? W/WindowManager: Force-removing child win Window{421832e8 u0 SurfaceView} from container Window{4215d150 u0 pytbepygame.test.pytbepygame/org.renpy.android.PythonActivity}
05-06 04:00:06.983 793-1738/? W/ActivityManager: Force removing ActivityRecord{42bf5d30 u0 pytbepygame.test.pytbepygame/org.renpy.android.PythonActivity t157}: app died, no saved state
05-06 04:00:07.033 793-1738/? I/WindowManager: Screen frozen for +629ms due to AppWindowToken{45bc4e50 token=Token{451d5010 ActivityRecord{42bf5d30 u0 pytbepygame.test.pytbepygame/org.renpy.android.PythonActivity t157}}}
```

The `on_pause` method is present. The app work well when the device is flipped in sdl2, but is closed with pygame backend.

kivy 1.9.1

It just happens to me?

thanks

**Comment by dessant** [comment] 2016-05-06 02:44
Possible duplicate of https://github.com/kivy/python-for-android/issues/730.

**Comment by kived** [comment] 2016-05-06 14:46
`05-06 04:00:06.533 9423-9443/? I/python: [INFO              ] [Android     ] Android wants to close our app.`

This means `onDestroy()` was called on your Activity. Please post a complete log rather than the small part you think is the problem.

**Comment by Tungsteno74** [comment] 2016-05-07 01:00
The bug happens in all the kivy app i have tested that use pygame as backend.

My test code:
```
<InnerScrollForm@ScrollView+GridLayout>
	size_hint_y: None
	height: dp(50)

BoxLayout:
	orientation: "vertical"
	BoxLayout:
		orientation: "vertical"
		BoxLayout:
			Button:
				text: "outScrollButton"
		InnerScrollForm:
			GridLayout:
				orientation: "vertical"
				cols: 1
				size_hint_y: None
				height: self.minimum_height			
				BoxLayout:
					orientation: "vertical"
					size_hint_y: None
					height: sp(100)
					Button:
						text: "theButton"							
				BoxLayout:
					id: "theBox"
					size_hint_y: None
					orientation: "vertical"
					height: sp(200)
					Button:
						text: "theInnButton"
					Button:
						text: "theInnButton"
					Button:
						text: "theInnButton"
					Button:
						text: "theInnButton"
					Button:
						text: "theInnButton"
					Button:
						text: "theInnButton"
				BoxLayout:
					size_hint_y: None
					orientation: "vertical"
					height: sp(80)
					Button:
						text: "yetAbutton"
					Button:
						text: "yetAbutton"
```

```
from kivy.app import App
from kivy.uix.button import Button

class mainApp(App):
    def on_pause(self):
        print "enter pause mode"
        return True

mainApp().run()
```

Full _logcat_ log and my _buildozer.spec_:
https://gist.github.com/Tungsteno74/c12892ac223f4270f5548ba5b10b80cd

**Comment by Zen-CODE** [comment] 2016-05-18 09:52
Having the same issue, but rears it's head differently. The app is set to portrait and runs fine. You can switch between apps and it works. When it wakes up from sleep, it crashes without any useful logs. 

When run in portrait mode, it wakes up without problems. There is an orientation change request just before the crash.

https://gist.github.com/Zen-CODE/d83fdd00d83b4e3721fa69d28a241745

**Comment by Zen-CODE** [comment] 2016-05-18 11:40
Can confirm that setting ' android.minapi = 13' in the buildozer.spec file worked for me.
@Tungsteno74. Have you tried that?

**Comment by Tungsteno74** [comment] 2016-05-21 16:04
@Zen-CODE  I tested right now and not work for me :( Always the same problem. When i flip the device, the app is closed (with no relevant error log)

**Comment by kollivier** [comment] 2016-06-15 23:10
Well, believe it or not, the close behavior is actually by design. :( See the "Caution" note on the Android Activity lifecycle about how it closes and restarts the app each time the app changes rotation:

https://developer.android.com/training/basics/activity-lifecycle/recreating.html

I guess completely reloading the app is one way to ensure it will load properly in the current rotation.... ;-) Doesn't explain the crash, but perhaps it relates to the app closing at an unexpected time? One other weird thing is that it seems Android has a Bundle instance object which saves certain app state and restores it automatically, and if it only partially restores the state or the app isn't expecting Android to do any restoration, it may be creating weird effects.

**Comment by Zen-CODE** [comment] 2016-07-13 06:08
@Tungsteno74. Please could you test and give some feedback using trunk (given kolliviers' merge: https://github.com/kivy/python-for-android/issues/797).

**Comment by Tungsteno74** [comment] 2016-08-19 14:34
@Zen-CODE  Hello. Sorry for late reply. I tried just now the master 0.33dev and given me the same issue.
I checked the kolliviers' merge and it should already be merged in the master. Confirm me that?

**Comment by Zen-CODE** [comment] 2016-08-19 15:45
Okay. And does setting 'android.minapi = 13' in the spec file work? This is still not clear.

**Comment by Tungsteno74** [comment] 2016-08-25 05:34
Unfortunately no.  At the moment the problem remains even with _android.minapi = 13_.

**Comment by Tungsteno74** [comment] 2016-08-26 02:35
@Zen-CODE  Ok i reinstall all the OS, buildozer and all dependencies and now work correctly with _0.33dev_ and _android.minapi = 13_.
Thanks at all!

**Comment by Zen-CODE** [comment] 2016-08-26 19:03
Awesome :-)

**Closed by Zen-CODE** 2016-08-26 19:03 UTC
