### ISSUE TITLE
P4A builds stable instead of master

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#300] opened 2014-11-16 10:24 UTC
Ubuntu 14.04 LTS, 64bit @ Win 8.1
Cython v0.21
according to https://code.google.com/p/kivy/downloads/detail?name=KivyLauncher-1.7.1.0.apk

distribute(without twisted):
https://gist.github.com/KeyWeeUsr/bb4ea4512f83f6612ab2

build:
https://gist.github.com/KeyWeeUsr/3c32d5cae2f72728b06e

Launcher works, but still v1.8.0, not master. Any ideas why/solutions?

**Comment by FeralBytes** [comment] 2015-02-13 05:08
Are you able to use [Buildozer](https://github.com/kivy/buildozer) instead? Then using the buildozer.spec file you can set android.p4a_dir to equal a directory into which you have cloned the master. Plus Buildozer gives you a lot more flexibility for other projects.

**Comment by KeyWeeUsr** [comment] 2015-02-13 07:28
If I remember correctly, buildozer worked good for apps with master. Couldn't change kivy master dir directly in p4a, though. Packaging the launcher alone didn't work, because there is no option in buildozer for that. Would be nice to have one.

**Comment by FeralBytes** [comment] 2015-02-13 07:32
Why do you need just the launcher, what are you trying to achieve?

**Comment by KeyWeeUsr** [comment] 2015-02-13 07:50
To edit and run scripts on android device "on the go", which it was probably created for. You know, there is launcher in google play, but the launcher is version 1.8.0, which is not really useful if you want to use new features from master. And as I see the store right now, the last update was last year, so.. yeah.

**Comment by FeralBytes** [comment] 2015-02-13 08:24
KeyWeeUsr: I think [this project, the kivy-remote-shell](https://github.com/kivy/kivy-remote-shell) will better fit your needs then. No you can't run scripts, but you could put them on the device and then import them. Then you can test code snippets or import modules all from a python shell that is on your android device. Also you can build the remote shell with [Buildozer](https://github.com/kivy/buildozer) which as I stated earlier then you can clone any version of P4A that you wish. You can also clone Kivy on your system or install a dev branch and you can run Buildozer using that version of Kivy. I currently have a modified version of Kivy 1.8.0 on my system that Buildozer uses when it compiles my Apps.
If this arrangement will meet your needs can you close this issue? If not I think the issue is really a Kivy issue not a P4A issue, do you agree?

**Comment by KeyWeeUsr** [comment] 2015-02-13 08:58
Actually, it doesn't. I need scripts to run, but thanks for the tip, I'll try it. But. How would you trigger some action that is based on touch? I don't need I/O console. And imagine printing non-english characters such as katakana in console. Not very useful this way, it's like using a wheelbarrow without wheel - you can, but...
Anyway, my problem is that I can't create launcher with kivy-master even if I force the folder with master through "P4A_kivy_DIR" in p4a, as there's no way how to do it through buildozer for now although brousch mentiones something(https://github.com/kivy/kivy/issues/2706#issuecomment-64729122). So it actually is an issue and not that I just really want to edit&run app on my knee in a bus or whatever. Maybe I was doing it wrong, but I used http://kivy.org/docs/guide/packaging-android.html#build-your-distribution and http://stackoverflow.com/questions/19834317/how-to-build-a-kivy-application-using-buildozer-and-the-latest-kivy , but the result was still 1.8.0 even when packaging an app.

**Comment by FeralBytes** [comment] 2015-02-13 09:15
OK the remote shell is not perfect, but I did wind up modifying it to have a button for some testing it; but still you are right it is only useful to a certain extent.
But you are using Ubuntu, using the daily/nightly builds which is master is as simple as installing the correct [PPA](http://kivy.org/docs/installation/installation-linux.html#ubuntu-11-10-or-newer). And yes those instructions talk about getting a newer version of P4A. P4A is not Kivy. You are trying to get Kivy beyond 1.8.0 which is master which is what you will get if you install the nightly/daily/dev repositories for Kivy.
As you can see [here](https://launchpad.net/~kivy-team/+archive/ubuntu/kivy-daily) that is truly following master as the version is 1.9.0 at this time.

**Comment by KeyWeeUsr** [comment] 2015-02-13 09:31
Maybe I didn't understand you well. Are you saying I don't use master of P4A? Because I use it. O_o Also P4A_kivy_dir should point to directory with kivy-master, which I've cloned/downloaded that time. So yeah, both were master and still ended up with 1.8.0

**Comment by FeralBytes** [comment] 2015-02-13 09:45
Where do you get this "P4A_kivy_dir" from. I see the distribute command that you ran above and I see that you set kivy=master... but that did not work. 

So what I am saying is just install kivy-daily on your Ubuntu system.
```
sudo add-apt-repository ppa:kivy-team/kivy-daily
sudo apt-get update
sudo apt-get install python-kivy
```
Then if you use Buildozer it will use your local installed copy of kivy which if you ran the commands above will be kivy-daily aka 1.9.0.

Since you say you cloned kivy master, what was the command you executed? And what is the current command you are running for distribute?

**Comment by KeyWeeUsr** [comment] 2015-02-13 10:25
In the links above, Ctrl+F "export P4A_kivy_DIR=/path/to/cloned/kivy/", used it, but don't know if the log didn't catch the command or I'd used it before the log began. It's in "Packaging with python-for-android" so it's not for buildozer, isn't it? Buildozer is just a tool to use P4A correctly. And as there is no option for creating Launcher with buildozer, I don't want to, or better said, I'm not able to use buildozer for this! Have you read the whole post before my previous one?
git clone? Just kidding.. the commands are in my first post + pointing through p4a_kivy_dir to kivy-master cloned kivy. I'm not working at this issue now, I won't kill another day with trying to build launcher with kivy-master through installing/uninstalling stuff, because "it's daily", if I don't know the result would be satisfying.
Buildozer can't do it, p4a somehow won't do it. What's wrong with p4a_kivy_dir it it's in docs and I'm using both p4a-master and kivy-master and why doesn't it work?

**Comment by FeralBytes** [comment] 2015-02-13 10:48
I don't mean to offend or upset you. But did you Ctrl+F "export" the first link, only lines 11 & 13 contain that keyword "export" and both are setting ANDROIDNDK. On your second link the keyword "export" is not found.
Yes I concur "P4A_kivy_DIR" is in the documentation, but I am unable to find what you actually ran to export it.
Yes you are right, how Launcher is created is not yet documented. But that is in the works as you linked to [earlier](https://github.com/kivy/kivy/issues/2706).
Yes, was just trying to give you some alternatives.
Again I did Ctrl+f your links for git clone but again I do not see you executing either of those commands.
I can understand the frustration and not wanting to waste more time on this issue. I am trying to close out some issues and that is why I am asking these questions, sorry if that has frustrated you further.
Can you please show me the 2 commands that I have requested so that I can verify that it does not work? Thank you for your help and time.

**Closed** 2015-05-06 16:21 UTC
