### ISSUE TITLE
Built APK fails with ImportError: dlopen failed on _clock.so

### ISSUE THREAD

**Issue by ngoonee** [kivy/python-for-android#998] opened 2017-01-27 01:45 UTC
I'm on current master (a924f9 24th Jan), trying to rebuild the launcher with more packages.

Starting an app from the launcher gives the following error in log. It never reaches my app's code, this happens during import.

01-27 07:21:04.271  7301  7409 I python  : [INFO   ] [Logger      ] Record log in /storage/emulated/0/kivy/songprez/.kivy/logs/kivy_17-01-27_3.txt
01-27 07:21:04.271  7301  7409 I python  : [INFO   ] [Kivy        ] v1.9.2-dev0
01-27 07:21:04.272  7301  7409 I python  : [INFO   ] [Python      ] v2.7.2 (default, Jan 27 2017, 06:36:47)
01-27 07:21:04.272  7301  7409 I python  : [GCC 4.8]
01-27 07:21:04.812  7301  7409 I python  :  Traceback (most recent call last):
01-27 07:21:04.812  7301  7409 I python  :    File "/storage/emulated/0/kivy/songprez/main.py", line 9, in <module>
01-27 07:21:04.813  7301  7409 I python  :      install_twisted_reactor()
01-27 07:21:04.813  7301  7409 I python  :    File "/home/ngoonee/.local/share/python-for-android/dists/songprezlauncher/private/lib/python2.7/site-packages/kivy/support.py", line 188, in install_twisted_reactor
01-27 07:21:04.814  7301  7409 I python  :    File "/home/ngoonee/.local/share/python-for-android/dists/songprezlauncher/private/lib/python2.7/site-packages/kivy/base.py", line 29, in <module>
01-27 07:21:04.815  7301  7409 I python  :    File "/home/ngoonee/.local/share/python-for-android/dists/songprezlauncher/private/lib/python2.7/site-packages/kivy/clock.py", line 362, in <module>
01-27 07:21:04.816  7301  7409 I python  :  ImportError: dlopen failed: file offset for the library "/data/user/0/org.kivy.customlauncher/files/app/lib/python2.7/site-packages/kivy/_clock.so" >= file size: 0 >= 0
01-27 07:21:04.849  7301  7409 I python  : Python for android ended.

**Comment by ngoonee** [comment] 2017-01-27 01:45
In case it's useful, here's my p4a line:-

p4a apk --requirements kivy==master,twisted,Whoosh,xmltodict,blinker,netifaces \
    --permission INTERNET \
    --permission WAKELOCK \
    --wakelock \
    --package=org.kivy.customlauncher \
    --dist_name=songprezlauncher \
    --name "Songprez Launcher" \
    --version=1.0.0 \
    --android_api 19 \
    --bootstrap=sdl2 \
    --launcher \
    --minsdk 19 \
    --orientation=user

**Comment by ngoonee** [comment] 2017-01-27 01:46
Issues https://github.com/kivy/python-for-android/issues/861 (possibly) and https://github.com/kivy/python-for-android/issues/992 (maybe not too likely) may be related.

**Comment by inclement** [comment] 2017-01-29 00:06
Do you get the same problem if you have no extra requirements (i.e. just kivy in the requirements)?

**Comment by ngoonee** [comment] 2017-01-30 18:12
Yes, identical error message. This is with kivy=master AND hostpython2 (python-for-android bug based on https://github.com/kivy/python-for-android/issues/620 which should already be fixed?).

Perhaps my installation of python-for-android isn't actually git master? My install line is

pip install git+https://github.com/kivy/python-for-android.git

**Comment by FeralBytes** [comment] 2017-02-12 01:50
@ngoonee try deleting the directories that I outline [here](https://github.com/kivy/python-for-android/issues/992#issuecomment-279189886) just to see.

**Comment by inclement** [comment] 2017-03-04 22:08
Is this still a problem using python-for-android and Kivy master branches?

**Comment by ngoonee** [comment] 2017-03-04 23:25
On kivy daf640 (Jan 13) and p4a 395c7e (Mar 4) I still get the same behavior. Running the 'animation' example using a basic build (--requirements master,hostpython2)

**Comment by ngoonee** [comment] 2017-03-04 23:44
Deleting the directories mentioned by @FeralBytes does not help, either.

**Comment by inclement** [comment] 2019-01-30 22:59
Closing as resolved, pretty sure this was caused by a bug loading libpymodules.so, which was fixed but has been obseleted anyway by replacing the python recipe.

**Closed by inclement** 2019-01-30 22:59 UTC
Labels: awaiting-reply
