### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void org.libsdl.app.SDLActivity.nativeQuit() (tried Java_org_libsdl_app_SDLActivity_nativeQuit and Java_org_libsdl_app_SDLActivity_nativeQuit__)

### ISSUE THREAD

**Issue by mkg20001** [kivy/python-for-android#1365] opened 2018-09-07 21:45 UTC
Google play pre-launch testing reports that the app crashes on some devices, while it doesn't on others and I'm clueless as to why that happens.

![screenshot](https://user-images.githubusercontent.com/7735145/45244297-82725f80-b2f7-11e8-83d8-f7ed3a779dec.png)
[logcat-galaxy-j1-ace.txt](https://github.com/kivy/python-for-android/files/2362592/logcat-galaxy-j1-ace.txt)
[logcat-galaxy-j6.txt](https://github.com/kivy/python-for-android/files/2362593/logcat-galaxy-j6.txt)
[logcat-lg-g6.txt](https://github.com/kivy/python-for-android/files/2362594/logcat-lg-g6.txt)
[logcat-mate-9.txt](https://github.com/kivy/python-for-android/files/2362595/logcat-mate-9.txt)
[logcat-moto-g4-play.txt](https://github.com/kivy/python-for-android/files/2362596/logcat-moto-g4-play.txt)
[logcat-p8-lite.txt](https://github.com/kivy/python-for-android/files/2362598/logcat-p8-lite.txt)
[logcat-pixel.txt](https://github.com/kivy/python-for-android/files/2362599/logcat-pixel.txt)

APKs: https://github.com/HelloZeroNet/ZeroNet-kivy/releases/tag/v0.6.3.2

**Comment by Petar-Luketina** [comment] 2018-10-03 03:02
Hey @mkg20001. Same issue. Have you resolved it by any chance? I'm using Python 2, and API 27.

**Comment by mkg20001** [comment] 2018-10-03 08:11
No, still no luck

**Comment by clevermindgames** [comment] 2018-11-09 02:28
I am getting crashes with this error in about 0.2% of daily sessions. I believe it might be happening when kivy app is in background and Android tries to kill it to free up the memory. It does not happen every time though and I could never reproduce it on my devices. The list of devices affected in Play store console is quite large, but it seems to be mostly related to Samsung Galaxy models and Huawei.

The stacktrace from Crashlytics is very similar if not the same (probably due to different version used):
```Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void org.libsdl.app.SDLActivity.nativeQuit() (tried Java_org_libsdl_app_SDLActivity_nativeQuit and Java_org_libsdl_app_SDLActivity_nativeQuit__)
       at org.libsdl.app.SDLActivity.nativeQuit(SDLActivity.java)
       at org.libsdl.app.SDLActivity.onDestroy(SDLActivity.java:250)
       at org.kivy.android.PythonActivity.onDestroy(PythonActivity.java:296)
       at android.app.Activity.performDestroy(Activity.java:7186)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1270)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4539)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4570)
       at android.app.ActivityThread.-wrap5(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1695)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6673)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)```

I do not have adb logs as I could not reproduce it myself.

**Comment by JonasT** [comment] 2019-01-31 01:52
@inclement could this possibly be the same as the `libpython3.6m.so.0.1` bug? (with the app failing to load the `.so`, I think that should give a similar error) If yes then this might be fixed now

@clevermindgames @mkg20001 could you possibly retest with latest master? (please note latest master currently requires a minimum api level of at least 21, and a target api level of at least 26)

**Comment by inclement** [comment] 2019-01-31 11:15
@JonasT Yes, I think it's likely that it was the same bug. Thanks, I missed this issue.

I'll close it for that reason, but it can be reopened if the bug does still occur.

**Closed by inclement** 2019-01-31 11:15 UTC

**Comment by LionReal** [comment] 2022-08-21 20:27
@inclement 
Hi, I'm getting the same error, how can I solve this problem? please your help.
Thank you.
Lionreal

Exception java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String org.libsdl.app.SDLActivity.nativeGetHint(java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativeGetHint and Java_org_libsdl_app_SDLActivity_nativeGetHint__Ljava_lang_String_2)
  at org.libsdl.app.SDLActivity.nativeGetHint
  at org.libsdl.app.SDLActivity.onBackPressed (SDLActivity.java:437)
  at android.app.Activity.onKeyUp (Activity.java:2975)
  at android.view.KeyEvent.dispatch (KeyEvent.java:2733)
  at android.app.Activity.dispatchKeyEvent (Activity.java:3267)
  at org.libsdl.app.SDLActivity.dispatchKeyEvent (SDLActivity.java:484)
  at com.android.internal.policy.DecorView.dispatchKeyEvent (DecorView.java:363)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:4744)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4616)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4158)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4211)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4177)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4304)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4185)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4361)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4158)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4211)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4177)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4185)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4158)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4211)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4177)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4337)
  at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent (ViewRootImpl.java:4498)
  at android.view.inputmethod.InputMethodManager$PendingEvent.run (InputMethodManager.java:2435)
  at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback (InputMethodManager.java:1998)
  at android.view.inputmethod.InputMethodManager.finishedInputEvent (InputMethodManager.java:1989)
  at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished (InputMethodManager.java:2412)
  at android.view.InputEventSender.dispatchInputEventFinished (InputEventSender.java:141)
  at android.os.MessageQueue.nativePollOnce
  at android.os.MessageQueue.next (MessageQueue.java:325)
  at android.os.Looper.loop (Looper.java:142)
  at android.app.ActivityThread.main (ActivityThread.java:6797)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)
