### ISSUE TITLE
Apps are too big (in size)

### ISSUE THREAD

**Issue by mid-kid** [kivy/python-for-android#202] opened 2014-02-01 22:59 UTC
Every separate kivy app installed has an identical copy of the libraries. That makes _every_ kivy app be about 20MB in size when only including the kivy library and it's dependencies. That's very big considering the actual content of the app.

There are several options to solve this problem I can think of:
- Go the necessitas/sl4a way and have an app for the libraries only. Users will be annoyed.
- Have every app include a piece of code to download precompiled libs (+ deps) to a .kivy folder in the sdcard. The sdcard needs to be available and have enough space.
- Use tinypy (though I doubt the compatibility + the project is pretty much moribund)
- Instead of extracting the python libraries from a zip, I think the python interpreter can load the zip directly. This will help a bit for size, but not for (startup) performance.
- I think nuitka can include all the necessary scripts into a single binary, then you just need several .so files (libpython, sdl, etc) and in my crappy theory, that should work. I don't know if this will reduce the size much, but at least you get performance, so that's a plus, I guess.
- Any ideas?
##

**Comment by hamedmohammadi** [comment] 2015-01-04 06:47
i dont know it can be helpfull but if there is a way to use jython in android we can add it as a jar file and we reduce the size of python itself

**Comment by mid-kid** [comment] 2015-01-04 09:15
Jython does not support python3, and afaik, it does not work with native libraries compiled for CPython, such as SDL.

**Comment by endolith** [comment] 2015-08-13 23:04
Kivy sounds perfect, being Python and cross-platform, but then all the apps it creates are huge for what they do, which makes me feel like it's not worth learning.

> Every kivy app is not 20MB, look at the showcase. It's 6MB, you need to trim your app. Kivy itself comes under 5-6 mb as evident by the showcase.

On Android it's 37 MB:

![kivy showcase 37 mb](https://cloud.githubusercontent.com/assets/58611/9263773/fd5eefa2-41ed-11e5-83fc-b2437c449ecc.png)

How do you "trim your app"?  Is this not automatic?

**Comment by inclement** [comment] 2016-01-11 00:17
@endolith: @akshayaurora was referring to the .apk file size (where 6-7MB is the minimum), not the unpacked size (where the ~30MB you see is a normal unpacked size for that minimal APK).

By trimming the app, I think @akshayaurora means removing parts of the python installation (and potentially our own app) that aren't necessary. Some such things are done automatically, where modules are unlikely to ever be useful on android, but doing it on a large scale would be extremely difficult as it's hard to inspect a python app and work out what modules it will need.

**Comment by J-qak** [comment] 2016-01-30 00:03
One utopic solution to this would be to have Python+Kivy commonly preinstaled on Android systems :-3

**Comment by v3ss0n** [comment] 2016-02-01 12:52
make an android virus that automatically spreads and install Kivy , Cordova + crosswalk , etc :P

**Comment by mardon86** [comment] 2016-03-10 08:05
Is there a way to create apk that contain only python script and additional module (without including python vm + kivy) ? and then have the apk detect if the python+kivy is installed. if python+kivy is not installed then download the python+kivy. Therefore every kivy app apk size will not too big.

**Comment by inclement** [comment] 2016-03-10 11:44
You could certainly do this. We would probably accept a PR adding such
functionality (in a reasonable option way), but are unlikely to work on
it any time soon because of the disadvantages this approach still has.

**Comment by admincoder** [comment] 2016-07-11 12:29
What about compiling the entire application with Nuitka and/or Cython and let the C/C++ compilers perform Dead Code Stripping/Elimination? @inclement, @tito 
This should strip out all unused parts (unreachable code) of Kivy, SDL2, Python, your own App and any external libraries.
I.e As Small As Possible (except for the code size increases made by Nuitka or Cython) 😄

**Comment by inclement** [comment] 2016-07-13 00:00
I think that Cython will mostly just make things bigger - I don't have any numbers to hand, but I'm pretty sure this has been discussed before. @tito probably has a stronger idea about it. For instance, Kivy is already heavily cythonised, this doesn't make it smaller in the APK.

I haven't looked at nuitka much, but I'd be surprised if the same weren't true.

In either case, I believe about 4MB of the 7MB basic APK size comes from the Python interpreter and other dependencies (now SDL2 etc., previously Pygame).

**Comment by admincoder** [comment] 2016-07-13 12:58
@inclement, you are right that cython makes the files bigger, especially when building for multiple architectures. I'm pretty sure nuitka also enlarges the files (not as much as cython though).

But the key idea here would be that the C/C++ compilers (Clang, GCC, MinGW, Visual C++ etc.) have Optimization options which include "Dead Code Elimination" (-o2 for GCC). This will remove unreachable code (unused symbols) from your entire project which includes Kivy and all dependencies.

Something so good always has a catch.

And that catch is that the entire project must be in C/C++ with nothing remaining in Python, as the interpreter will also be stripped of any unused portions of the VM (from the perspective of the Compiler) rendering parts of python code foreign to the interpreter. With that in mind, this should only be done at the end of the development cycle just before deployment and not before.

**Comment by mcroni** [comment] 2016-07-18 18:33
another way you can reduce the size of kivy apps is by editing the file called blacklist.txt
this file includes all the modules or dependencies in kivy and you can blacklist them to exclude them(libraries) and this will make your kivy file smaller in size when compiling

**Comment by mcroni** [comment] 2016-07-18 18:34
[blacklist.txt](https://github.com/kivy/python-for-android/files/369842/blacklist.txt)
thats an example of a blacklist.txt file

**Comment by admincoder** [comment] 2016-07-18 21:14
@mcroni, 
Blacklist.txt is quite a handy way to exclude any unused modules, if that is good enough for you. 

But passing an entire C/C++ project with a compiler optimization option such as https://en.m.wikipedia.org/wiki/Dead_code_elimination, will work with more granularity than a human would ever want to:
It removes unused variables, functions and classes from even every module you do decide to include (even parts of the python interpreter). 

This won't be possible by editing the blacklist.txt file, and if it works as expected, YOU WILL NEVER HAVE TO WORRY ABOUT DEPENDENCIES.

Pretty cool right...(Don't take the capitalization personally, just wanted to emphasize that point, as dependency management can be a nightmare when trying to optimize for size).

**Comment by KeyWeeUsr** [comment] 2016-07-18 21:24
@admincoder This is all in a theoretical way. Try to make it this way and show some numbers here. If there's no rapid change or even increased size with cythonizing everything(which should), then it doesn't really matter. That's why cython is used in the cases where it _should_ be used(speed) and not where it _could_ be used e.g. even creating a widget.

**Comment by mcroni** [comment] 2016-07-18 22:56
well @admincoder i experimented with this a bit and make some mistakes but now i know which modules not to touch, i now have a customized blacklist for my builds. it doesnt hurt at all

**Comment by admincoder** [comment] 2016-07-19 00:19
@keyweeusr,
I'm sorry, I have a tendency to think about solutions without actually implementing them; due to a lack of experience and time. 
Please refer to my previous post where I explicitly say Nuitka and/or Cython: to be more clear, Cython for speed ONLY, and Nuitka for compatibility and a pure C/C++ code base should be the ideal steps to achieve what I am talking about. You may even use Nuitka alone, apart from the cythonized modules Kivy provides. 

@mcroni,
If it doesn't hurt, it doesn't hurt. But I think this post is for people it hurts. 
IMHO, Kivy has the potential to target smart watches and embedded boards, not to mention other platforms. And also, disk space on smartphones isn't the same as desktops; users may decide to choose another app, delete your app later, or not download it at all simply because of it's size (I've done all three myself).

**Comment by cdb1019** [comment] 2017-03-28 02:45
What is the latest on this issue?  Have any improvements been made?  Is Kivy still under active development?

**Comment by inclement** [comment] 2017-03-28 21:36
Kivy and python-for-android are both actively developed (you can check
the recent commits in either of them), but the technical barriers
described earlier in this thread have not really changed.

**Comment by KeyWeeUsr** [comment] 2017-03-28 22:13
@cdb1019 I have a small list of files&folders that could be removed from the Python packaged into APK archive, but a testing is needed:

folders:
* distutils
* email (if not needed)
* xml (if not needed)

files:
* pdb.doc
* pdb files
* profiling files
* this
* timeit
* SMTP

maybe:
* pprint (never used it directly)

That kills another ~1.86MB from unpacked Python (~7.5MB for me). The rest is only about cutting off stuff from Kivy that you don't need such as behaviors, complex widgets, kivy logos, keyboard layouts, fonts, effects, extras, recorder(input), some modules, storage (if you don't use it), tools (aren't packaged, I think). For all that you'll need to check if they aren't imported or referenced somewhere else (and that's a matter of change always). We can't really strip the Kivy parts as we don't have a clue what a user might use, but we _might be able_ to strip Python a little bit more in the future.

**Comment by kamathln** [comment] 2017-04-10 08:53
Anyone has plans to make an Android fork/mod/ROM with Kivy built in? - In such a way that all App developers need to do is package the main.py and main.kivy (obfuscated if necessary), and necessary support files not included with kivy. The install file also comes with a requirements.txt which the internal pip interprets. 

Just a thought that crossed my mind.

**Comment by mcroni** [comment] 2017-04-10 21:13
I think what you're saying is too vague,, are you referring to something
like a kivy launcher but can also compile the apk at the same time??

**Comment by kamathln** [comment] 2017-04-11 05:17
Yes, It is purposefully vague at the moment. It is more of a problem statement than the solution. The final aim is to be able to distribute APKs or may be some other installer without the whole load of the Interpreter + libraries in every APK/installer. Also, the required python libraries can be

**Comment by kamathln** [comment] 2017-04-11 05:23
Now this comment has nothing to do with the above idea. Have we tried experimenting with xz/lzma compression instead of zip? I know, when the app is decompressed initially it is finally going to occupy the same space, but at least it can reduce the compressed size?

**Comment by frmdstryr** [comment] 2017-07-05 03:43
Perhaps a modified version of [cx_Freeze](http://cx-freeze.readthedocs.io/en/latest/overview.html) could be used? 

With cx_Freeze, you tell it which modules are needed for your app (already in the kivy requirements), then it scans all those modules and finds their dependencies (you can add ones it can't find automatically) and packs ONLY the needed python modules and their dependencies into a single `library.zip` file. Also it renames all .so files (only from required modules / packages) in the format `package.name.so` and places them in a single folder.

```
build/library.zip # all data, py/pyc files
build/libx.so
build/libpython.so
build/my.pkg.so
etc...
```

Once this is done:
1. The library.zip could be extracted and packaged in the apk (unzipped). Since the apk is a zip, if the apk were added to the python path, the python files could then be imported directly with the standard zipimporter (maybe would need a modified path).
2. All the necessary .so files could be copied to the lib folder so they are extracted upon install.

Pros:
1. Automatically remove all unused modules (thus reducing overall footprint, i've seen 3x-4x reductions on desktop apps)
2. Save space of unpacked python assets (current cost is  tar.gz size + unpacked size) as they would be loaded right from the apk (excluding .so files)
3. Remove startup time cost of unpacking assets on first run (since this would be done at install)

Cons:
1. Would need tested and implemented
2. Add a minimal startup loading time due to importing from zip (Importing the stdlib.zip from crystax only takes 89ms to load, so this may be negligible)
3. Loader would need to know to import so files based on dotted name instead of path.

**Comment by kamathln** [comment] 2017-07-06 04:05
hi

**Comment by frmdstryr** [comment] 2017-07-07 11:32
Perhaps a modified version of [cx_Freeze](https://github.com/anthony-tuininga/cx_Freeze) could be used?

With cx_Freeze, you tell it which modules are needed for your app (already in the kivy requirements), then it scans all those modules and finds their dependencies (you can add ones it can't find automatically) and packs ONLY the needed python modules and their dependencies into a single library.zip file. Also it renames all .so files (only from required modules / packages) in the format package.name.so and places them in a single folder.

```
build/library.zip # all data, py/pyc files
build/libx.so
build/libpython.so
build/my.pkg.so
etc...
```
Once this is done:

1. The library.zip could be extracted and packaged in the apk (unzipped). Since the apk is a zip, if the apk were added to the python path, the python files could then be imported directly with the standard zipimporter (maybe would need a modified path).
2. All the necessary .so files could be copied to the lib folder so they are extracted upon install.

Pros:

1. Automatically remove all unused modules (thus reducing overall footprint, i've seen 3x-4x reductions on desktop apps)
2. Save space of unpacked python assets (current cost is tar.gz size + unpacked size) as they would be loaded right from the apk (excluding .so files)
3. Remove startup time cost of unpacking assets on first run (since this would be done at install)

Cons:
1. Would need tested and implemented
2. Adds a startup loading time due to importing from zip (Importing only the stdlib.zip from crystax only takes 89ms to load)
3. Loader would need to know to import so files based on dotted name instead of path.

Edit:
I tested this by packing everything into a zip, putting the so files in a single location, hacking the import to load the correct so files, and the startup time was rather slow (extra 4 seconds) due to importing from the zipfile. So some alternative way needs investigated.

Perhaps extraction could be sped up using [czipfile](https://pypi.python.org/pypi/czipfile/1.0.0), or the library contents could be loaded into memfs or something.

**Comment by frmdstryr** [comment] 2017-07-12 13:11
I found out how to have all the `.so` files copied during app **install** (not on first run!) and get loaded properly from the app. 

Doing it this way you can support multiple arch's in one apk, EVEN when your python requirements  has compiled components as only the actual py files are in the assets folder. You can also then compress all the python libs into a zip and import them (although it's slower at the moment).  

1. You have to move all `.so` files to your `libs/<arch>/` folder (where libs is the jniDir) 
2. Rename them to `lib.<pkg>.<of>.module.so` (if they dont start with lib, android won't copy them from the apk automatically)
3. Add the module importer to your app before importing anything using the modules and add it with `sys.meta_path.append(AndroidFinder())`
4. Add the `APK_LIB_DIR` to your environment, can be set via the jni and retrieved using `getApplicationInfo().nativeLibraryDir` in your activity.

```python

'''
Copyright (c) 2017, Jairus Martin.

Distributed under the terms of the MIT License.

The full license is in the file COPYING.txt, distributed with this software.

Created on July 10, 2017

@author: jrm
'''
import os
import sys
import imp
from glob import glob


class AndroidLoader(object):
    """ Loads renamed .so files from the app's lib folder"""

    def load_module(self, mod):
        try:
            return sys.modules[mod]
        except KeyError:
            pass

        lib = AndroidFinder.so_modules[mod]
        m = imp.load_dynamic(mod, lib)
        sys.modules[mod] = m
        return m


class AndroidFinder(object):
    """ Loads renamed so files from the app's lib folder"""
    so_modules = {}

    def __init__(self):
        #: Find all included so files
        lib_dir = os.environ['APK_LIB_DIR']

        for lib in glob('%s/lib.*.so'%lib_dir):
            name = lib.split("/")[-1] # Lib filename
            mod = ".".join(name.split(".")[1:-1])  # Strip lib and so
            AndroidFinder.so_modules[mod] = lib


    def find_module(self, mod, path = None):
        if mod in self.so_modules:
            return AndroidLoader()
        return None


```

**Comment by kamathln** [comment] 2017-07-13 03:56
@endolith I know I am more than 18months late .. But have you checked if the apk generated previously is also getting included in the app? When my app size started doubling every build , I noticed that the previous generated apk was getting bundled into the current apk ..

So, over the last few iterations, my development pattern has morphed somewhat .. I keep all the files that go into the real app in the src directory, and give p4a the src directory as the private folder. The blacklist.txt , project config and other files remain in the project's root directory. I suggest Kivy developers using python-for-android to switch to this pattern. Feels clean.

**Comment by kamathln** [comment] 2017-07-13 03:57
@frmdstryr  Please look into https://developer.android.com/studio/build/configure-apk-splits.html if you are interested in building multiple architectures. I myself haven't tried it, but is definitely on my todo list.

**Comment by inclement** [comment] 2017-07-13 17:49
@frmdstryr That's extremely encouraging, thanks for the research! I'll certainly try this

**Comment by frmdstryr** [comment] 2017-07-22 00:45
I was able to get about a 15% reduction by using [pyminifier](https://github.com/liftoff/pyminifier/tree/master/pyminifier). 

Interestingly, it reduces the py files about about 50%, but when compiled to pyo the difference is only ~15%. Still, took it from 9.6 MB to 8.2 MB. Slight improvement.

**Comment by KeyWeeUsr** [comment] 2017-07-22 07:09
@frmdstryr If you can, try *only* the minification on the whole Python's `Lib` folder recursively. Maybe the best would be *not* to include it to the recipe, but use only some console arg and do it before actually packaging the application i.e. right before the `private.mp3` creation.

I remember trying `pyminifier` with `pyinstaller` and there it worked just fine even with the obfuscation, however on android we might get into troubles with that. I tried a similar thing with replacing 4 spaces with 1 tab, but the size change wasn't that significant for such a harsh operation and with Kivy itself the change was almost invisible + when you start mixing tabs & spaces in the app, well... :D In any case, minification might even backfire, so if included, we probably shouldn't do it automatically.

**Comment by kamathln** [comment] 2017-07-22 13:28
@frmdstryr Has anyone researched on [Ultimate Executable Packer](https://upx.github.io/) ? The code is currently way out of my league .. can it be adapted for python pyc/pyo , etc.. ?

**Comment by KeyWeeUsr** [comment] 2017-07-22 14:35
Every such compression will need decompression on the device. It doesn't really matter how quickly you compress if you end up with the loading screen displayed for a minute. You can't just make the whole interpreter disappear with compressing, you need to **remove** files from it to actually make a usable difference. Just saying.

**Comment by frmdstryr** [comment] 2017-07-22 14:45
@KeyWeeUsr That's what I'm doing, except I'm using crystax python 2. Currently I extract the `stdlib.zip` and `site-packages` to one folder and run minify on all py files within it recursively so it minifies(?) everything except my app code files. I added a flag to p4a to enable/disable it.

> In any case, minification might even backfire, so if included, we probably shouldn't do it automatically.

Yes, exactly. If it does get added, it should be disabled by default as it's more of a final product optimization anyways. 

Minify does screw up some files, for instance the `sre*.py` modules used by `re` in the python `Lib` fails to import (even though it compiles to pyo fine?). I also have it skip the `join_multiline_pairs` minification as that seemed to cause a lot of issues. But some method of exclusion would also be needed because every user has different requirements. 


@kamathln p4a already compresses everything with `tar.gz` so there won't be much of a gain there.

**Comment by frmdstryr** [comment] 2017-07-22 15:11
It would be interesting if some sort of bundler could be used like what is commonly done with javascript ([webpack](https://github.com/webpack/webpack) for example). [react-native](https://facebook.github.io/react-native/) does this on release builds.  It wouldn't save  space (unless you can do minification on the bundle) but you could use the trick to have it extracted during install and avoid the startup extraction.

Pros:
1. Importing would be one file, which "could" potentially save a lot of system calls and speedup importing (theoretically, I have no data to back it up). Currently python itself is ~700 files which is a lot of blocking system calls. 
2. It could be extracted on install by tricking android into thinking it's a native lib, saving extraction time on first startup.

Cons:
1. Would still need to extract any data files.
2. Would need copied for each arch (if multiple are used)

The only "packer" I found was [pinliner](https://github.com/Akrog/pinliner). I ran a few tests, and it can't bundle multiple packages and modules at the moment (but does work nice for a single package), and it doesn't pack pyc/pyo files. If these were implemented, the python `Lib` and `site-packages` could be packed into one big file, then it could be named something that tricks android into copying it with the native modules (ex `lib.pymodules.so`) during install and imported from there.

**Comment by kamathln** [comment] 2017-07-26 15:21
@frmdstryr Thanks for correcting my assumption. Had assumed it is plain tar. Tried recompressing it with tar.xz instead. My private.mp3 came down from 6.3mb to 4.7mb . The decompression speed was 3x slower though.  (still much faster than bz2) . The comparizon was on a laptop though. Planning to try on my phone using termux .

**Comment by kamathln** [comment] 2017-07-26 16:06
```
$ time bzcat t.tar.bz2 > /dev/null

real    0m3.672s
user    0m3.520s
sys     0m0.030s
$ time zcat t.tgz > /dev/null

real    0m0.489s
user    0m0.420s
sys     0m0.020s

$ time xzcat t.tar.xz > /dev/null

real    0m1.191s
user    0m1.110s
sys     0m0.040s
$
```

**Comment by kamathln** [comment] 2017-07-26 16:08
The tar.gz is simply a rename. tar.xz and tar.bz2 are created with ....
```
zcat t.tar.gz2 | xz > t.tar.xz
```
....technique

**Comment by frmdstryr** [comment] 2017-10-11 16:28
https://github.com/lz4/lz4


Compressor | Ratio | Compression | Decompression
-- | -- | -- | --
memcpy | 1.000 | 7300 MB/s | 7300 MB/s
LZ4 fast 8 (v1.7.3) | 1.799 | 911 MB/s | 3360 MB/s
LZ4 default (v1.7.3) | 2.101 | 625 MB/s | 3220 MB/s
LZO 2.09 | 2.108 | 620 MB/s | 845 MB/s
QuickLZ 1.5.0 | 2.238 | 510 MB/s | 600 MB/s
Snappy 1.1.3 | 2.091 | 450 MB/s | 1550 MB/s
LZF v3.6 | 2.073 | 365 MB/s | 820 MB/s
Zstandard 1.1.1 -1 | 2.876 | 330 MB/s | 930 MB/s
Zstandard 1.1.1 -3 | 3.164 | 200 MB/s | 810 MB/s
zlib deflate 1.2.8 -1 | 2.730 | 100 MB/s | 370 MB/s
LZ4 HC -9 (v1.7.3) | 2.720 | 34 MB/s | 3240 MB/s
zlib deflate 1.2.8 -6 | 3.099 | 33 MB/s | 390 MB/s

LZ4 HZ -9 seems like a VERY good alternative to targz.

**Comment by tasen-sp** [comment] 2020-07-21 19:25
Can I do it by just deleting blank lines, comments,unused things from kivy???

**Comment by inclement** [comment] 2020-07-21 19:28
No, you won't get much if any gain from that. We already compile and ship bytecode and that doesn't help the size much.

**Comment by tasen-sp** [comment] 2020-07-21 19:34
Should I use pyminifier?

**Comment by tshirtman** [comment] 2020-08-13 15:59
the issue is not the size of python code, it's mostly the size of binaries, like python itself, and all the cpython extensions (like kivy, but also others), that can quickly run into the megabyte range.

I'm not sure this issue is actionable, it's too broad, there will always be reasons to argue that apps are "too big", i'd rather see someone analyse and point at specific issues that can be fixed to make the apk / installed size smaller, and to have these fixed independently. So i'm going to close it, if another maintainer disagree, feel free to reopen, if an user sees a specific issue to fix to help address the point of this issue, feel free to open another one describing the exact issue you see.

**Closed by tshirtman** 2020-08-13 16:00 UTC

**Comment by omeco4christ** [comment] 2022-06-12 13:10
Can this be achieved by removing unused libraries and packages?
