### ISSUE TITLE
Compilation Error at ARM Environment

### ISSUE THREAD

**Issue by kiok46** [kivy/python-for-android#352] opened 2015-03-30 07:32 UTC
This error shows up when i type "  ./distribute.sh -m "kivy"  "command.
I am at the ARM environment.
I have tried everything to fix this error, but now I need help.

Note: If you want me to edit something, please let me know.

"ERROR"

```
creating Makefile
./configure --host=arm-eabi OPT= --prefix=/home/kd/python-for-android/build/python-install --enable-shared --disable-toolbox-glue --disable-framework
make -j5 HOSTPYTHON=/home/kd/python-for-android/build/python/Python-2.7.2/hostpython HOSTPGEN=/home/kd/python-for-android/build/python/Python-2.7.2/hostpgen CROSS_COMPILE_TARGET=yes INSTSONAME=libpython2.7.so
cp: cannot stat ‘HOSTPYTHON=/home/kd/python-for-android/build/python/Python-2.7.2/hostpython’: No such file or directory
First install (failing..)
./Modules/zlibmodule.c:8:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make: *** [Modules/zlibmodule.o] Error 1
make: *** Waiting for unfinished jobs....

second install
/usr/bin/install -c -m 644 ./Include/cStringIO.h /home/kd/python-for-android/build/python-install/include/python2.7
./Modules/zlibmodule.c:8:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make: *** [Modules/zlibmodule.o] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/install -c -m 644 ./Include/cellobject.h /home/kd/python-for-android/build/python-install/include/python2.7

/usr/bin/install -c -m 644 pyconfig.h /home/kd/python-for-android/build/python-install/include/python2.7/pyconfig.h
Leaving ARM environment
cp: cannot create regular file ‘/home/kd/python-for-android/build/python-install/bin/python.host’: No such file or directory
```
##

**Comment by asdri** [comment] 2015-04-02 07:42
Help please I have the same issue..

**Comment by asdri** [comment] 2015-04-02 07:44
This is what I get when compiling with "buildozer -v android debug" or "buildozer android debug" :

./Modules/zlibmodule.c:8:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make: *** [Modules/zlibmodule.o] Error 1
make: *** Waiting for unfinished jobs....
Leaving ARM environment
cp: cannot create regular file ‘/home/asdri/testapp/.buildozer/android/platform/python-for-android/build/python-install/bin/python.host’: No such file or directory
# Command failed: ./distribute.sh -m "kivy" -d "myapp"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.

**Comment by asdri** [comment] 2015-04-02 07:51
I just got a simple "Hello World" type snippet which's the following:

```
import kivy
kivy.require('1.9.0')

from kivy.app import App
from kivy.uix.button import Button

print dir(Button)

class Index(App):
	def build(self):
		return Button(text='Click me')

Index().run()
```

**Comment by olymk2** [comment] 2015-04-02 07:53
usually this is down to the version of cython your using you need a different version of cython for 1.8 and 1.9 try changing distribute to kivy==master to use 1.9 i cant remember the exact version you need for 1.8 but google around and you should find the answer. 

see if that helps

**Comment by olymk2** [comment] 2015-04-02 11:56
did you try kivy==master ? for me it will not compile kivy 1.8 probably because my cython is to new what is your version ?

if it is actually a missing file thats not caused by the build then i dont know perhaps someone else will

**Comment by asdri** [comment] 2015-04-02 13:03
@olymk2 Do you mean `pip install kivy==master`? I tried that and it tells me there's no master version available:

```
Collecting kivy==master
  Could not find a version that satisfies the requirement kivy==master (from versions: 1.0.1a0, 1.0.2a0, 1.0.3a0, 1.0.4b0, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0)
  No distributions matching the version for kivy==master
```

**Comment by olymk2** [comment] 2015-04-02 13:08
nope ./distribute.sh -m "kivy" or in buildozer.spec change kivy to kivy==master and see if it works. if you use kivy you get 1.8 if you use kivy==master you get 1.9 which is just about to be released by looks of it :)

**Comment by Kozubi** [comment] 2015-07-08 06:46
I encountered same problem and for me this helped:
```# (int) Android API to use
android.api = 19```

**Comment by hvorovk** [comment] 2016-12-03 17:00
Nothing here is not helping me. How do I fix it? I even hello world I can not build.
```
/Modules/zlibmodule.c:8:18: fatal error: zlib.h: No such file or directory
compilation terminated.
```

**Comment by moshen212** [comment] 2016-12-11 01:41
I faced to similar python.host location error... but i found a suggest in below issue link:
https://github.com/kivy/python-for-android/issues/231
this worked

**Comment by hvorovk** [comment] 2016-12-11 02:36
this does not work!

**Comment by inclement** [comment] 2016-12-11 12:44
@hvorovk Your error seems to indicate you don't have zlib. Make sure you install it, including a -dev package if available, as you need the zlib.h file. You may also need the 32 bit version.

**Comment by inclement** [comment] 2017-09-29 21:52
Closing as this issue relates to the old toolchain which is no longer supported. Please open a new issue if you experience this problem with the current master branch.

**Closed by inclement** 2017-09-29 21:52 UTC
Labels: need-analysis
