### ISSUE TITLE
buildozer can't download hostpython2

### ISSUE THREAD

**Issue by dildeolupbiten** [kivy/python-for-android#1132] opened 2017-10-03 13:48 UTC
**OS:** Ubuntu 17.04
**Python:** 3.5.2

I'm new to kivy. When i try to type `buildozer -v android debug`, the compilation process failed when downloading hostpython2. Can anyone help me to fix this problem?

The full error message is below:

```
tanberk@kutlu:~/İndirilenler$ buildozer -v android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' paket yönetim programı sürüm 1.18.10 (amd64).
Bu bir özgür yazılımdır; kopyalama şartları için GNU Genel Kamu Lisansı
sürüm 2 ya da daha yenisine bakın. Hiçbir garanti verilmez.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10,<1.12.5" "jinja2" "six"'
# Cwd None
# Apache ANT found at /home/tanberk/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/tanberk/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/tanberk/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/tanberk/İndirilenler/.buildozer/android/platform/build'
# Cwd /home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found multiple valid dependency orders:
[INFO]:        ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:        ['hostpython2', 'pygame_bootstrap_components', 'python2', 'sdl', 'six', 'pygame', 'pyjnius', 'kivy']
[INFO]:        ['hostpython3crystax', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    Using the first of these: ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name myapp and recipes (kivy)
[INFO]:    Dist will also contain modules () installed from pip
[INFO]:    -> running cp -r /home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonfo...(and 127 more)
[INFO]:    -> directory context /home/tanberk/İndirilenler/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2
[INFO]:    <- directory context /home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is ['hostpython2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python2', 'sdl2', 'six', 'pyjnius', 'kivy']
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/tanberk/İndirilenler/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> directory context /home/tanberk/İndirilenler/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> running rm -f .mark-Python-2.7.2.tar.bz2                                                                                          
[INFO]:    Downloading hostpython2 from http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1857, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1873, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1889, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.5/urllib/request.py", line 2112, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2077, in http_error_302
    headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2108, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1857, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1877, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1873, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1889, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.5/urllib/request.py", line 2112, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2077, in http_error_302
    headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2108, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1873, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1889, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.5/urllib/request.py", line 2112, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2077, in http_error_302
    headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2108, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1857, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 916, in <module>
    main()
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 913, in main
    ToolchainCL()
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 514, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 192, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/build.py", line 550, in build_recipes
    recipe.download_if_necessary()
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 344, in download_if_necessary
    self.download()
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 384, in download
    self.download_file(url, filename)
  File "/home/tanberk/İndirilenler/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 150, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.5/urllib/request.py", line 1732, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1877, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1873, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1889, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.5/urllib/request.py", line 2112, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2077, in http_error_302
    headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2108, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1873, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1889, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.5/urllib/request.py", line 2112, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2077, in http_error_302
    headers, data)
  File "/usr/lib/python3.5/urllib/request.py", line 2108, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1908, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1857, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] [Errno socket error] [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/tanberk/İndirilenler/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
tanberk@kutlu:~/İndirilenler$ 

```

**Comment by inclement** [comment] 2017-11-18 17:41
I couldn't reproduce this at the time, but I think it may have been caused by using http instead of https, which I've now fixed in Kivy master.

**Closed by inclement** 2017-11-18 17:41 UTC

**Comment by OptimusGREEN** [comment] 2017-12-21 18:43
I'm having this exact same issue now with a fresh master install

**Comment by FionnOConnor** [comment] 2018-05-15 10:11
Hi,
I'm rather new to Python and Kivy. Unfortunately I'm getting the same error as above.
Would really appreciate any guidance on how to rectify this if anyone has any ideas.

Thanks.

**Comment by dildeolupbiten** [comment] 2018-05-15 10:37
Hi,
If you use Python3, you must download [Crystax ndk package](https://www.crystax.net/en/download) instead the android ndk package. Then you must define the android_ndk_path in **buildozer.spec** file. 
Like:
`# in my case crystax-ndk is in .buildozer folder.`
`android.ndk_path = ~/.buildozer/crystax-ndk`

**Comment by FionnOConnor** [comment] 2018-05-15 12:57
Hi dildeolupbiten,

Thanks, I've done the above. Unfortunately I'm hitting a new error after this as below.

[INFO]:    ccache is missing, the build will not be optimized in the future.
[WARNING]: ndk_platform doesn't exist: /usr/local/bin/platforms/android-19/arch-arm
[WARNING]: Could not find toolchain subdirectory!
[WARNING]: Could not find any toolchain for arm-linux-androideabi!
[WARNING]: Missing executable: autoconf is not installed
[WARNING]: Missing executable: automake is not installed
[WARNING]: Missing executable: libtoolize is not installed
[ERROR]:   python-for-android cannot continue; aborting
# Command failed: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -m pythonforandroid.toolchain create --dist_name=debkapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/fionnoconnor35/Temp/DEBK/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by inclement** [comment] 2018-06-11 17:26
@chanckstephen I think this is some macOS related problem, possibly relating to the openssl version, but I don't really know.
