### ISSUE TITLE
Error while in gradlew

### ISSUE THREAD

**Issue by piontk** [kivy/python-for-android#1740] opened 2019-03-05 17:21 UTC
I'm trying to generate the APK via buildozer and I got this while in Gradlew:

```
[INFO]:    Selecting java build tool:
[INFO]:    Detected highest available build tools version to be 28.0.3
[INFO]:        Building with gradle, as gradle executable is present
[DEBUG]:   -> running gradlew assembleDebug

[DEBUG]:   ebugJ> Task :compileDebugJavaWithJavac 
[DEBUG]:   orm/b/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1947: error: cannot find symbol
[DEBUG]:   	            case MotionEvent.ACTION_BUTTON_PRESS:
[DEBUG]:   	                            ^
[DEBUG]:   	  symbol:   variable ACTION_BUTTON_PRESS
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1948: error: cannot find symbol
[DEBUG]:   	            case MotionEvent.ACTION_BUTTON_RELEASE:
[DEBUG]:   	                            ^
[DEBUG]:   	  symbol:   variable ACTION_BUTTON_RELEASE
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1951: error: cannot find symbol
[DEBUG]:   	                if (action == MotionEvent.ACTION_BUTTON_PRESS) {
[DEBUG]:   	                                         ^
[DEBUG]:   	  symbol:   variable ACTION_BUTTON_PRESS
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1954: error: cannot find symbol
[DEBUG]:   	                else if (action == MotionEvent.ACTION_BUTTON_RELEASE) {
[DEBUG]:   	                                              ^
[DEBUG]:   	  symbol:   variable ACTION_BUTTON_RELEASE
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:435: error: cannot find symbol
[DEBUG]:   	                haptic.vib.vibrate(VibrationEffect.createOneShot(length, vibeValue));
[DEBUG]:   	                                   ^
[DEBUG]:   	  symbol:   variable VibrationEffect
[DEBUG]:   	  location: class SDLHapticHandler_API26
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:666: error: cannot find symbol
[DEBUG]:   	                            x = event.getAxisValue(MotionEvent.AXIS_RELATIVE_X);
[DEBUG]:   	                                                              ^
[DEBUG]:   	  symbol:   variable AXIS_RELATIVE_X
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:667: error: cannot find symbol
[DEBUG]:   	                            y = event.getAxisValue(MotionEvent.AXIS_RELATIVE_Y);
[DEBUG]:   	                                                              ^
[DEBUG]:   	  symbol:   variable AXIS_RELATIVE_Y
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:709: error: cannot find symbol
[DEBUG]:   	            return event.getAxisValue(MotionEvent.AXIS_RELATIVE_X);
[DEBUG]:   	                                                 ^
[DEBUG]:   	  symbol:   variable AXIS_RELATIVE_X
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:719: error: cannot find symbol
[DEBUG]:   	            return event.getAxisValue(MotionEvent.AXIS_RELATIVE_Y);
[DEBUG]:   	                                                 ^
[DEBUG]:   	  symbol:   variable AXIS_RELATIVE_Y
[DEBUG]:   	  location: class MotionEvent
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:768: error: cannot find symbol
[DEBUG]:   	            case InputDevice.SOURCE_MOUSE_RELATIVE:
[DEBUG]:   	                            ^
[DEBUG]:   	  symbol:   variable SOURCE_MOUSE_RELATIVE
[DEBUG]:   	  location: class InputDevice
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:813: error: cannot find symbol
[DEBUG]:   	                SDLActivity.getContentView().requestPointerCapture();
[DEBUG]:   	                                            ^
[DEBUG]:   	  symbol:   method requestPointerCapture()
[DEBUG]:   	  location: class View
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:816: error: cannot find symbol
[DEBUG]:   	                SDLActivity.getContentView().releasePointerCapture();
[DEBUG]:   	                                            ^
[DEBUG]:   	  symbol:   method releasePointerCapture()
[DEBUG]:   	  location: class View
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:831: error: cannot find symbol
[DEBUG]:   	            SDLActivity.getContentView().requestPointerCapture();
[DEBUG]:   	                                        ^
[DEBUG]:   	  symbol:   method requestPointerCapture()
[DEBUG]:   	  location: class View
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:116: error: cannot find symbol	
[DEBUG]:   	                    channelConfig = AudioFormat.CHANNEL_OUT_7POINT1_SURROUND;
[DEBUG]:   	                                               ^
[DEBUG]:   	  symbol:   variable CHANNEL_OUT_7POINT1_SURROUND
[DEBUG]:   	  location: class AudioFormat
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:328: error: cannot find symbol
[DEBUG]:   	        return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
[DEBUG]:   	                                                                                 ^
[DEBUG]:   	  symbol:   variable READ_BLOCKING
[DEBUG]:   	  location: class AudioRecord
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:328: error: cannot find symbol
[DEBUG]:   	        return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
[DEBUG]:   	                                                                                                             ^
[DEBUG]:   	  symbol:   variable READ_NON_BLOCKING
[DEBUG]:   	  location: class AudioRecord
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:336: error: cannot find symbol
[DEBUG]:   	            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
[DEBUG]:   	                                                                                     ^
[DEBUG]:   	  symbol:   variable READ_BLOCKING
[DEBUG]:   	  location: class AudioRecord
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:336: error: cannot find symbol
[DEBUG]:   	            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
[DEBUG]:   	                                                                                                                 ^
[DEBUG]:   	  symbol:   variable READ_NON_BLOCKING
[DEBUG]:   	  location: class AudioRecord
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:345: error: cannot find symbol
[DEBUG]:   	            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
[DEBUG]:   	                                                                                     ^
[DEBUG]:   	  symbol:   variable READ_BLOCKING
[DEBUG]:   	  location: class AudioRecord
[DEBUG]:   	/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:345: error: cannot find symbol
[DEBUG]:   	            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
[DEBUG]:   	                                                                                                                 ^
[DEBUG]:   	  symbol:   variable READ_NON_BLOCKING
[DEBUG]:   	  location: class AudioRecord
[DEBUG]:   	Note: Some input files use or override a deprecated API.
[DEBUG]:   	Note: Recompile with -Xlint:deprecation for details.
[DEBUG]:   	Note: Some input files use unchecked or unsafe operations.
[DEBUG]:   	Note: Recompile with -Xlint:unchecked for details.
[DEBUG]:   	20 errors
[DEBUG]:   	
[DEBUG]:   	
[DEBUG]:   	FAILURE: Build failed with an exception.
[DEBUG]:   	
[DEBUG]:   	* What went wrong:
[DEBUG]:   	Execution failed for task ':compileDebugJavaWithJavac'.
[DEBUG]:   	> Compilation failed; see the compiler error output for details.
[DEBUG]:   	
[DEBUG]:   	* Try:
[DEBUG]:   	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[DEBUG]:   	
[DEBUG]:   	* Get more help at https://help.gradle.org
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED in 42s
[DEBUG]:   	15 actionable tasks: 15 executed
[DEBUG]:   	
[DEBUG]:   	
Exception in thread background thread for pid 17711:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tiago/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/tiago/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/tiago/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/tiago/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/gradlew assembleDebug

  STDOUT:

> Task :compileDebugJavaWithJavac 
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1947: error: cannot find symbol
            case MotionEvent.ACTION_BUTTON_PRESS:
                            ^
  symbol:   variable ACTION_BUTTON_PRESS
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1948: error: cannot find symbol
            case MotionEvent.ACTION_BUTTON_RELEASE:
                            ^
  symbol:   variable ACTION_BUTTON_RELEASE
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1951: error: cannot find symbol
                if (action == MotionEvent.ACTION_BUTTON_PRESS) {
                                         ^
  symbol:   variable ACTION_BUTTON_PRESS
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLActivity.java:1954: error: cannot find symbol
                else if (action == MotionEvent.ACTION_BUTTON_RELEASE) {
                                              ^
  symbol:   variable ACTION_BUTTON_RELEASE
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:435: error: cannot find symbol
                haptic.vib.vibrate(VibrationEffect.createOneShot(length, vibeValue));
                                   ^
  symbol:   variable VibrationEffect
  location: class SDLHapticHandler_API26
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:666: error: cannot find symbol
                            x = event.getAxisValue(MotionEvent.AXIS_RELATIVE_X);
                                                              ^
  symbol:   variable AXIS_RELATIVE_X
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:667: error: cannot find symbol
                            y = event.getAxisValue(MotionEvent.AXIS_RELATIVE_Y);
                                                              ^
  symbol:   variable AXIS_RELATIVE_Y
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:709: error: cannot find symbol
            return event.getAxisValue(MotionEvent.AXIS_RELATIVE_X);
                                                 ^
  symbol:   variable AXIS_RELATIVE_X
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:719: error: cannot find symbol
            return event.getAxisValue(MotionEvent.AXIS_RELATIVE_Y);
                                                 ^
  symbol:   variable AXIS_RELATIVE_Y
  location: class MotionEvent
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:768: error: cannot find symbol
            case InputDevice.SOURCE_MOUSE_RELATIVE:
                            ^
  symbol:   variable SOURCE_MOUSE_RELATIVE
  location: class InputDevice
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:813: error: cannot find symbol
                SDLActivity.getContentView().requestPointerCapture();
                                            ^
  symbol:   method requestPointerCapture()
  location: class View
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:816: error: cannot find symbol
                SDLActivity.getContentView().releasePointerCapture();
                                            ^
  symbol:   method releasePointerCapture()
  location: class View
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLControllerManager.java:831: error: cannot find symbol
            SDLActivity.getContentView().requestPointerCapture();
                                        ^
  symbol:   method requestPointerCapture()
  location: class View
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:116: error: cannot find symbol
                    channelConfig = AudioFormat.CHANNEL_OUT_7POINT1_SURROUND;
                                               ^
  symbol:   variable CHANNEL_OUT_7POINT1_SURROUND
  location: class AudioFormat
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:328: error: cannot find symbol
        return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
                                                                                 ^
  symbol:   variable READ_BLOCKING
  location: class AudioRecord
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:328: error: cannot find symbol
        return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
                                                                                                             ^
  symbol:   variable READ_NON_BLOCKING
  location: class AudioRecord
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:336: error: cannot find symbol
            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
                                                                                     ^
  symbol:   variable READ_BLOCKING
  location: class AudioRecord
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:336: error: cannot find symbol
            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
                                                                                                                 ^
  symbol:   variable READ_NON_BLOCKING
  location: class AudioRecord
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:345: error: cannot find symbol
            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
                                                                                     ^
  symbol:   variable READ_BLOCKING
  location: class AudioRecord
/home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/src/main/java/org/libsdl/app/SDLAudioManager.java:345: error: cannot find symbol
            return mAudioRecord.read(buffer, 0, buffer.length, blocking ? AudioRecord.READ_BLOCKING : AudioRecord.READ_NON_BLOCKING);
                                                                                                                 ^
  symbol:   variable READ_NON_BLOCKING
  location: class AudioRecord
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
20 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
15 actionable tasks: 15 executed




  STDERR:

[INFO]:    STDOUT (last 20 lines of 133):
	
	
FAILURE: Build failed with an exception.	
	
* What went wrong:	
Execution failed for task ':compileDebugJavaWithJavac'.	
> Compilation failed; see the compiler error output for details.	
	
* Try:	
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.	
	
* Get more help at https://help.gradle.org	
	
BUILD FAILED in 42s	
15 actionable tasks: 15 executed	

[INFO]:    STDERR:
	
[INFO]:    COMMAND:
cd /home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp && /home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/gradlew assembleDebug

[WARNING]: ERROR: /home/tiago/Documentos/.buildozer/android/platform/build/dists/rainhaapp/gradlew failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No compiled python is present to zip, skipping.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name rainhaapp --name 'Abastecimento Rainha' --version 0.2 --package org.test.rainhaapp --android_api 22 --minsdk 21 --ndk-api 21 --private /home/tiago/Documentos/.buildozer/android/app --permission INTERNET --icon /home/tiago/Documentos/abastecimento-rainha/busw.png --orientation portrait --copy-libs --arch armeabi-v7a --color=always --storage-dir="/home/tiago/Documentos/.buildozer/android/platform/build" --ndk-api=21
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

My .spec file:
```

[app]

# (str) Title of your application
title = Abastecimento Rainha

# (str) Package name
package.name = rainhaapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = 

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.2

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = kivy,sqlite3,datetime,python3

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
icon.filename = /home/tiago/Documentos/abastecimento-rainha/busw.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
android.api = 22

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
# android.sdk = 20

# (str) Android NDK version to use
android.ndk = 17b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes = /home/tiago/Documentos/recipes

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
build_dir = /home/tiago/Documentos/.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

Cython version = 0.28.3

**Comment by piontk** [comment] 2019-03-18 19:01
@AndreMiras any news about it?

**Comment by AndreMiras** [comment] 2019-03-18 20:07
Hey! Why me? :sweat_smile: 
Yes sure! https://github.com/kivy/python-for-android/issues/1697

**Comment by inclement** [comment] 2019-04-07 19:38
Closing as a duplicate of #1697. Resolution: target Android 26+, see linked issue for details.

**Closed by inclement** 2019-04-07 19:38 UTC
