### ISSUE TITLE
After successfully building app, its crashes with this error, using firebase-admin

### ISSUE THREAD

**Issue by rEHui-MbIcJIu** [kivy/python-for-android#2854] opened 2023-07-12 05:51 UTC
### Checklist

- [ ] I have a short, runnable example that reproduces the issue
- [x] I reproduced the problem with the latest development version (`p4a.branch = develop`)

### Versions

- Python: 3
- OS:Android
- Kivy: 2.2.0
- Cython:
- OpenJDK:

### Description
I used firebase and it needs grpc but grpc needs special reciep i think

### buildozer.spec

Spec file:
```
`
package.name = emergencyApp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,gif
version = 0.1
requirements = python3,kivy==2.2.0 ,pyttsx3,googlemaps, firebase-admin, bcrypt,kivymd==1.1.1, requests, openssl, urllib3, chardet, idna, jwt, cryptography,pyparsing, pil, google-auth, cachetools, pyasn1, pyasn1_modules, rsa,google-api-python-client, google-cloud-storage, google-cloud-firestore, google-api-core,  protobuf, cachecontrol, gcloud, google-cloud, httplib2,grpcio, google-cloud-core, proto-plus, google-cloud-translate,google-cloud-datastore, googleapis-common-protos, google-api-python-client , six, google, google-auth-httplib2, google-auth-oauthlib
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = android.permission.INTERNET, (name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)
android.api = 33
android.minapi = 21
android.ndk = 25b
`
```

### Logs
`
```
Traceback (most recent call last):

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/app/main.py", line 33, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/google/cloud/firestore/__init__.py", line 18, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/google/cloud/firestore_v1/__init__.py", line 27, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/google/cloud/firestore_v1/_helpers.py", line 22, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/google/api_core/gapic_v1/__init__.py", line 16, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/google/api_core/gapic_v1/config.py", line 23, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/grpc/__init__.py", line 22, in <module>

File "/mnt/c/Users/rEHui/Desktop/wsl/APP/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/emergencyApp/arm64-v8a/grpc/_compression.py", line 20, in <module>

ImportError: dlopen failed: "/data/data/org.test.emergencyapp/files/app/_python_bundle/site-packages/grpc/_cython/cygrpc.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

Python for android ended.
```
`
I think its need a recipe, idk how to make ones, even with the link:
https://github.com/grpc/grpc/blob/master/setup.py

**Comment by RobertFlatt** [comment] 2023-07-15 00:27
https://github.com/Android-for-Python/Android-for-Python-Users#em_x86_64-instead-of-em_aarch64

> I think its need a recipe, idk how to make ones, even with the link:
> https://github.com/grpc/grpc/blob/master/setup.py

yes
https://github.com/Android-for-Python/Android-for-Python-Users#creating-a-recipe

see also 
https://github.com/Android-for-Python/INDEX-of-Examples#cloud-storage-examples

**Comment by misl6** [comment] 2023-07-15 14:44
Duplicate of #2853

**Closed by misl6** 2023-07-15 14:44 UTC
