### ISSUE TITLE
Importing numpy yields: TypeError: add_docstring() argument 2 must be str, not None

### ISSUE THREAD

**Issue by brentpicasso** [kivy/python-for-android#1988] opened 2019-09-19 18:38 UTC
### Versions

* Python: 2.7
* OS: Linux
* Kivy: 1.11.1
* Cython: 0.28.5

### Description

importing numpy generates the following error when executing on Android:

09-19 11:35:14.025 21284 21846 I python  :  TypeError: add_docstring() argument 2 must be str, not None
09-19 11:35:14.025 21284 21846 I python  : Python for android ended.

Repro: 

helloworld app, with numpy imported. 

### buildozer.spec

Command:
```
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = Podium

# (str) Package name
package.name = podium

# (str) Package domain (needed for android/ios packaging)
package.domain = com.autosportlabs

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,ttf,json,svg,cfg,obj,mtl,glsl,zip,sql

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests, bin, .git, install, build_tools

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py

# (str) Application versioning (method 2)
# version = 1.2.0

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3, kivy, pygments

requirements = python2, kivy==1.11.1, numpy, scipy, openssl, pyopenssl, android, websocket-client, pygments, raven, pyjnius, https://github.com/autosportlabs/plyer/archive/master.zip, sqlalchemy, contextlib2, podium_api==0.0.13, https://github.com/nskrypnik/kivy3/zipball/master
# ffpyplayer==v4.1.0, ffpyplayer_codecs, 

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = resource/images/app_splash_screen.png

# (str) Icon of the application
icon.filename = resource/images/app_icon_256x256.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = all

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1


#
# Android specific
#

# (list) Permissions
android.permissions = INTERNET, BLUETOOTH, BLUETOOTH_ADMIN , WRITE_EXTERNAL_STORAGE, WAKE_LOCK, ACCESS_FINE_LOCATION, CHANGE_WIFI_STATE, CHANGE_NETWORK_STATE, ACCESS_WIFI_STATE, ACCESS_NETWORK_STATE

# (int) Android API to use
android.api = 28

# (int) Minimum API required (8 = Android 2.2 devices)
android.minapi = 21

# (str) Android NDK version to use
android.ndk = 17c

# (int) Android NDK API to use (optional)
android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

p4a.branch = release-2019.07.08

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir = ../python-for-android

# (list) python-for-android whitelist
#android.p4a_whitelist =

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = jar/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar
android.add_src = java/src/

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =
#android.add_src = java/src/

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
android.wakelock = True

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

#
# iOS specific
#

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1


# -----------------------------------------------------------------------------
# List as sections
#
# You can define all the "list" as [section:key].
# Each line will be considered as a option to the list.
# Let's take [app] / source.exclude_patterns.
# Instead of doing:
#
#     [app]
#     source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
# This can be translated into:
#
#     [app:source.exclude_patterns]
#     license
#     data/audio/*.wav
#     data/images/original/*
#


# -----------------------------------------------------------------------------
# Profiles
#
# You can extend section / key with a profile
# For example, you want to deploy a demo version of your application without
# HD content. You could first change the title to add "(demo)" in the name
# and extend the excluded directories to remove the HD content.
#
#     [app@demo]
#     title = My Application (demo)
#
#     [app:source.exclude_patterns@demo]
#     images/hd/*
#
# Then, invoke the command line with the "demo" profile:
#
#     buildozer --profile demo android debug

```

### Logs

```
09-19 11:35:14.021 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/app/autosportlabs/uix/analysis/analysiswidget.py", line 36, in <module>
09-19 11:35:14.021 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/app/autosportlabs/uix/gauge/gaugeselectionview.py", line 14, in <module>
09-19 11:35:14.022 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/app/autosportlabs/uix/gauge/gaugefactory.py", line 10, in <module>
09-19 11:35:14.022 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/app/autosportlabs/uix/gauge/timegapgauge.py", line 46, in <module>
09-19 11:35:14.022 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/python-installs/podium/scipy/__init__.py", line 62, in <module>
09-19 11:35:14.023 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/python-installs/podium/numpy/__init__.py", line 142, in <module>
09-19 11:35:14.023 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/python-installs/podium/numpy/core/__init__.py", line 40, in <module>
09-19 11:35:14.024 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/python-installs/podium/numpy/core/multiarray.py", line 74, in <module>
09-19 11:35:14.024 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/python-installs/podium/numpy/core/overrides.py", line 186, in decorator
09-19 11:35:14.024 21284 21846 I python  :    File "/home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/python-installs/podium/numpy/core/overrides.py", line 150, in decorator
09-19 11:35:14.025 21284 21846 I python  :  TypeError: add_docstring() argument 2 must be str, not None
09-19 11:35:14.025 21284 21846 I python  : Python for android ended.

```

**Comment by brentpicasso** [comment] 2019-09-19 19:03
Also reproduces with  p4a.branch = stable

**Comment by AndreMiras** [comment] 2019-09-19 20:26
Thanks for the bug report. So this is a on-device runtime error. Could you share a reproduction case with the `main.py`. I suspect this error can also be reproduced directly on the host computer. I suspect it's not p4a related.

**Comment by brentpicasso** [comment] 2019-09-19 23:12
This does not reproduce when the app runs from the command line (Linux). 

It only reproduces on Android. 

Repro:
```
import kivy
kivy.require('1.11.1')

from kivy.app import App
from kivy.uix.label import Label
import numpy

class MyApp(App):

    def build(self):
        return Label(text='Hello world')

if __name__ == '__main__':
    MyApp().run()
```

**Comment by AndreMiras** [comment] 2019-09-20 08:40
Nice thank you! Could you now share the complete run stacktrace that you get with this example so we can see the starting line.

**Comment by opacam** [comment] 2019-09-20 09:17
@brentpicasso , seeing your buildozer.spec file  I assume that You tested with outdated p4a branches:
  - `release-2019.07.08`
  - `stable`

So, I'm wondering...Is this issue reproducible with **android NDK r19b** and current p4a's **develop branch**?

**Note:** Numpy recipe has been changed since the last published release (**v2019.08.09**), so this may not be an issue anymore...

**Comment by brentpicasso** [comment] 2019-09-20 18:45
Problem also reproduces with

p4a.branch = release-2019.08.09

Checking development branch.

**Comment by brentpicasso** [comment] 2019-09-20 19:30
p4a.branch = master and ndk r19  fails to build:

```
[INFO]:    Building libffi for armeabi-v7a
[ERROR]:   Build failed: Couldn't find executable for CC. This indicates a problem locating the arm-linux-androideabi-gcc executable in the Android NDK, not that you don't have a normal compiler installed. Exiting.
Searching path are: '/bigdrive/ext_home/brent/.buildozer/android/platform/android-ndk-r19b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/:/bigdrive/ext_home/brent/.buildozer/android/platform/android-ndk-r19b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/bigdrive/ext_home/brent/.buildozer/android/platform/android-ndk-r19b:/bigdrive/ext_home/brent/.buildozer/android/platform/android-sdk/tools:/home/brent/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/jdk/bin:/opt/gcc-arm-none-eabi-4_9-2014q4/bin/:/opt/gnuarm-4.0.2/bin/:/home/brent/.rvm/bin:/home/brent/.rvm/bin'
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=podium --bootstrap=sdl2 --requirements=python2,kivy==1.11.1,numpy,scipy,openssl,pyopenssl,android,websocket-client,pygments,raven,pyjnius,https://github.com/autosportlabs/plyer/archive/master.zip,sqlalchemy,contextlib2,podium_api==0.0.13,https://github.com/nskrypnik/kivy3/zipball/master --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/brent/git-projects/podium_app/.buildozer/android/platform/build" --ndk-api=21
# ENVIRONMENT:
#     WINDOWID = '75497482'
#     MANDATORY_PATH = '/usr/share/gconf/ubuntu.mandatory.path'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm-data/brent'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     UPSTART_EVENTS = 'xsession started'
#     XDG_CURRENT_DESKTOP = 'Unity'
#     UNITY_HAS_3D_SUPPORT = 'true'
#     XDG_SESSION_TYPE = 'x11'
#     QT_IM_MODULE = 'ibus'
#     LOGNAME = 'brent'
#     USER = 'brent'
#     PATH = '/home/brent/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/jdk/bin:/opt/gcc-arm-none-eabi-4_9-2014q4/bin/:/opt/gnuarm-4.0.2/bin/:/home/brent/.rvm/bin:/home/brent/.rvm/bin'
#     XDG_VTNR = '7'
#     GNOME_KEYRING_CONTROL = ''
#     PACKAGES_PATH = '/home/brent/.buildozer/android/packages'
#     DISPLAY = ':0'
#     KIGITHUB = 'https://github.com/KiCad'
#     LANG = 'en_US.UTF-8'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     XAUTHORITY = '/home/brent/.Xauthority'
#     LANGUAGE = 'en_US'
#     SESSION_MANAGER = 'local/brent-desktop:@/tmp/.ICE-unix/2459,unix/brent-desktop:/tmp/.ICE-unix/2459'
#     SHLVL = '3'
#     QT_LINUX_ACCESSIBILITY_ALWAYS_ON = '1'
#     QT_QPA_PLATFORMTHEME = 'appmenu-qt5'
#     CLUTTER_IM_MODULE = 'xim'
#     UNITY_DEFAULT_PROFILE = 'unity'
#     UPSTART_INSTANCE = ''
#     QT_ACCESSIBILITY = '1'
#     SESSION = 'ubuntu'
#     SESSIONTYPE = 'gnome-session'
#     XMODIFIERS = '@im=ibus'
#     GPG_AGENT_INFO = '/home/brent/.gnupg/S.gpg-agent:0:1'
#     KICAD_PATH = '/usr/share/kicad'
#     QT4_IM_MODULE = 'xim'
#     GTK2_MODULES = 'overlay-scrollbar'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     ANDROIDSDK = '/home/brent/.buildozer/android/platform/android-sdk'
#     COMPIZ_BIN_PATH = '/usr/bin/'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     INSTANCE = ''
#     COMPIZ_CONFIG_PROFILE = 'ubuntu'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     VTE_VERSION = '4205'
#     GDMSESSION = 'ubuntu'
#     IM_CONFIG_PHASE = '1'
#     UPSTART_JOB = 'unity7'
#     GNOME_KEYRING_PID = ''
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     ANDROIDMINAPI = '21'
#     XDG_SESSION_ID = 'c2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:abstract=/tmp/dbus-zlHZ8BJUK8'
#     _ = '/usr/local/bin/buildozer'
#     DEFAULTS_PATH = '/usr/share/gconf/ubuntu.default.path'
#     GTK_IM_MODULE = 'ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     UPSTART_SESSION = 'unix:abstract=/com/ubuntu/upstart-session/1000/2227'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg'
#     GTK_MODULES = 'gail:atk-bridge:unity-gtk-module'
#     ANDROIDNDK = '/home/brent/.buildozer/android/platform/android-ndk-r19b'
#     GDM_LANG = 'en_US'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop'
#     PWD = '/home/brent/git-projects/podium_app'
#     JOB = 'unity-settings-daemon'
#     ANDROIDAPI = '28'
#     HOME = '/home/brent'
#     XDG_MENU_PREFIX = 'gnome-'
#     XDG_SEAT = 'seat0'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
Still could not find ./.buildozer/android/platform/build/dists/podium/templates/AndroidManifest.tmpl.xml after debug build. Aborting.
Failed to prepare Buildozer. Aborting.
```

**Comment by brentpicasso** [comment] 2019-09-20 19:35
p4a.branch = release-2019.08.09 and android.ndk = 19b also fails

```
[INFO]:    -> running configure
[INFO]:    <- directory context /home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2       
[INFO]:    -> running cp Modules/Setup.dist /home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/other_builds...(and 59 more)
[INFO]:    -> running make -j 8 -C /home/brent/git-projects/podium_app/.buildozer/android/platform/build/build/other_builds/hostpyth...(and 36 more)
[INFO]:    <- directory context /home/brent/git-projects/podium_app/.buildozer/android/platform/python-for-android                                             
[INFO]:    Building libffi for armeabi-v7a
[ERROR]:   Build failed: Couldn't find executable for CC. This indicates a problem locating the arm-linux-androideabi-gcc executable in the Android NDK, not that you don't have a normal compiler installed. Exiting.
Searching path are: '/bigdrive/ext_home/brent/.buildozer/android/platform/android-ndk-r19b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/:/bigdrive/ext_home/brent/.buildozer/android/platform/android-ndk-r19b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/bigdrive/ext_home/brent/.buildozer/android/platform/android-ndk-r19b:/bigdrive/ext_home/brent/.buildozer/android/platform/android-sdk/tools:/home/brent/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/jdk/bin:/opt/gcc-arm-none-eabi-4_9-2014q4/bin/:/opt/gnuarm-4.0.2/bin/:/home/brent/.rvm/bin:/home/brent/.rvm/bin'
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=podium --bootstrap=sdl2 --requirements=python2,kivy==1.11.1,numpy,scipy,openssl,pyopenssl,android,websocket-client,pygments,raven,pyjnius,https://github.com/autosportlabs/plyer/archive/master.zip,sqlalchemy,contextlib2,podium_api==0.0.13,https://github.com/nskrypnik/kivy3/zipball/master --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/brent/git-projects/podium_app/.buildozer/android/platform/build" --ndk-api=21
# ENVIRONMENT:
#     WINDOWID = '75497482'
#     MANDATORY_PATH = '/usr/share/gconf/ubuntu.mandatory.path'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm-data/brent'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     UPSTART_EVENTS = 'xsession started'
#     XDG_CURRENT_DESKTOP = 'Unity'
#     UNITY_HAS_3D_SUPPORT = 'true'
#     XDG_SESSION_TYPE = 'x11'
#     QT_IM_MODULE = 'ibus'
#     LOGNAME = 'brent'
#     USER = 'brent'
#     PATH = '/home/brent/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/jdk/bin:/opt/gcc-arm-none-eabi-4_9-2014q4/bin/:/opt/gnuarm-4.0.2/bin/:/home/brent/.rvm/bin:/home/brent/.rvm/bin'
#     XDG_VTNR = '7'
#     GNOME_KEYRING_CONTROL = ''
#     PACKAGES_PATH = '/home/brent/.buildozer/android/packages'
#     DISPLAY = ':0'
#     KIGITHUB = 'https://github.com/KiCad'
#     LANG = 'en_US.UTF-8'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     XAUTHORITY = '/home/brent/.Xauthority'
#     LANGUAGE = 'en_US'
#     SESSION_MANAGER = 'local/brent-desktop:@/tmp/.ICE-unix/2459,unix/brent-desktop:/tmp/.ICE-unix/2459'
#     SHLVL = '3'
#     QT_LINUX_ACCESSIBILITY_ALWAYS_ON = '1'
#     QT_QPA_PLATFORMTHEME = 'appmenu-qt5'
#     CLUTTER_IM_MODULE = 'xim'
#     UNITY_DEFAULT_PROFILE = 'unity'
#     UPSTART_INSTANCE = ''
#     QT_ACCESSIBILITY = '1'
#     SESSION = 'ubuntu'
#     SESSIONTYPE = 'gnome-session'
#     XMODIFIERS = '@im=ibus'
#     GPG_AGENT_INFO = '/home/brent/.gnupg/S.gpg-agent:0:1'
#     KICAD_PATH = '/usr/share/kicad'
#     QT4_IM_MODULE = 'xim'
#     GTK2_MODULES = 'overlay-scrollbar'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     ANDROIDSDK = '/home/brent/.buildozer/android/platform/android-sdk'
#     COMPIZ_BIN_PATH = '/usr/bin/'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     INSTANCE = ''
#     COMPIZ_CONFIG_PROFILE = 'ubuntu'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     VTE_VERSION = '4205'
#     GDMSESSION = 'ubuntu'
#     IM_CONFIG_PHASE = '1'
#     UPSTART_JOB = 'unity7'
#     GNOME_KEYRING_PID = ''
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     ANDROIDMINAPI = '21'
#     XDG_SESSION_ID = 'c2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:abstract=/tmp/dbus-zlHZ8BJUK8'
#     _ = '/usr/local/bin/buildozer'
#     DEFAULTS_PATH = '/usr/share/gconf/ubuntu.default.path'
#     GTK_IM_MODULE = 'ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     UPSTART_SESSION = 'unix:abstract=/com/ubuntu/upstart-session/1000/2227'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg'
#     GTK_MODULES = 'gail:atk-bridge:unity-gtk-module'
#     ANDROIDNDK = '/home/brent/.buildozer/android/platform/android-ndk-r19b'
#     GDM_LANG = 'en_US'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop'
#     PWD = '/home/brent/git-projects/podium_app'
#     JOB = 'unity-settings-daemon'
#     ANDROIDAPI = '28'
#     HOME = '/home/brent'
#     XDG_MENU_PREFIX = 'gnome-'
#     XDG_SEAT = 'seat0'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
Still could not find ./.buildozer/android/platform/build/dists/podium/templates/AndroidManifest.tmpl.xml after debug build. Aborting.
Failed to prepare Buildozer. Aborting.
```

**Comment by brentpicasso** [comment] 2019-09-24 01:47
So far py4a latest and ndk 19b fails to build. Anything else I should provide for repro?

**Comment by brentpicasso** [comment] 2019-10-10 14:13
Ping to keep this issue alive. Have I submitted enough information? How can I help further?

**Comment by AndreMiras** [comment] 2019-10-11 10:17
I can usually build APK OK, but I'm running on `p4a.branch = develop` and buildozer master (unreleased).

**Comment by opacam** [comment] 2019-10-14 20:45
@brentpicasso, @AndreMiras is right, you should pass the build phase, if you don't pass it, probably it's because you have cached builds in your `~.buildozer` folder. Just remove that folder and try it again and you should pass the build, but...even if you pass the build, you will receive exactly the same error, I just reproduced your issue using  one of p4a's testapps (`setup_testapp_python2`) for archs `arm64-v8a` and `armeabi-v7a` **importing numpy in python2 leads to  an TypeError**: 

`TypeError: add_docstring() argument 2 must be str, not None`

@Brentpicasso, **thanks for reporting this issue**, I'm working on a fix for that, but I must say that I think that should be fixed elsewhere (probably at numpy or cpython side) but, since I doubt that this get fixed from the mentioned repos, I will propose a solution to p4a team :wink:

**Thanks again man, and sorry for the delay with the response, I don't have so much time these days.**

**Note:** There is an open issue at numpy about this error [here](https://github.com/numpy/numpy/issues/13248)

**Comment by brentpicasso** [comment] 2019-10-14 22:42
Great, thank you for the update.

**Closed** 2019-10-15 00:16 UTC
