### ISSUE TITLE
Issue with pyaudio and portaudio

### ISSUE THREAD

**Issue by Unicornasaurous** [kivy/python-for-android#2535] opened 2021-12-30 19:55 UTC
### Versions

- Python: 3.9
- OS: Arch
- Kivy: 2.0.0
- Cython: 0.29.26
- OpenJDK: 17.0.1

### Description

I am attempting to make an android app using kivy, compiled with buildozer, that produces a google text to speech sound via saved mp3 file when a button is pressed. It depends on pyaudio for gTTS to work. However, I seem to be getting an error when building pyaudio that says that the portaudio header, portaudio.h, does not exist. I am not very familiar with how all of this works, but I would have to assume that this is an issue with pyaudio not having access to portaudio and that a recipe is needed for this to work. 

### buildozer.spec

Command:
```sh
buildozer -v android debug 

```

Spec file:
```
app]

# (str) Title of your application
title = Hunter is gay test

# (str) Package name
package.name = gay

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,urllib3,idna,charset-normalizer,certifi,requests,pygments,Kivy-Garden,docutils,six,pillow,kivy,click,SpeechRecognition,PyAudio,playsound,kivymd,gTTS


# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

### Logs

```
    Running command /home/tim/Documents/projects/Test/.buildozer/android/platform/build-armeabi-v7a/build/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9n239646/pyaudio_56aedd1ed76841b596da5c19049a43ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9n239646/pyaudio_56aedd1ed76841b596da5c19049a43ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jmpp9vqh/install-record.txt --single-version-externally-managed --home /tmp/pip-target-0gq5endc --compile --install-headers /tmp/pip-target-0gq5endc/include/site/python3.8/pyaudio
    Ignoring "sys._home = value" override
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.8
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    /home/tim/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -I/home/tim/Documents/projects/Test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/home/tim/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -I/home/tim/Documents/projects/Test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/gay/include/python3.8 -fPIC -I/home/tim/Documents/projects/Test/.buildozer/android/platform/build-armeabi-v7a/build/venv/include -I/usr/local/include/python3.8 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.8/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command '/home/tim/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang' failed with exit status 1
    Running setup.py install for pyaudio ... error
ERROR: Command errored out with exit status 1: /home/tim/Documents/projects/Test/.buildozer/android/platform/build-armeabi-v7a/build/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9n239646/pyaudio_56aedd1ed76841b596da5c19049a43ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9n239646/pyaudio_56aedd1ed76841b596da5c19049a43ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jmpp9vqh/install-record.txt --single-version-externally-managed --home /tmp/pip-target-0gq5endc --compile --install-headers /tmp/pip-target-0gq5endc/include/site/python3.8/pyaudio Check the logs for full command output.


  STDERR:

# Command failed: /home/tim/Documents/projects/Test/bin/python -m pythonforandroid.toolchain create --dist_name=gay --bootstrap=sdl2 --requirements=python3,urllib3,idna,charset-normalizer,certifi,requests,pygments,Kivy-Garden,docutils,six,pillow,kivy,click,SpeechRecognition,PyAudio,playsound,kivymd,gTTS --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/tim/Documents/projects/Test/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     WINDOWID = '127926279'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/home/tim/.config/kdedefaults:/etc/xdg'
#     LANGUAGE = ''
#     SHELL_SESSION_ID = '447997fede2f4d0dacb98d2b88d3ed2b'
#     DESKTOP_SESSION = 'plasma'
#     GTK_RC_FILES = '/etc/gtk/gtkrc:/home/tim/.gtkrc:/home/tim/.config/gtkrc'
#     XCURSOR_SIZE = '24'
#     GTK_MODULES = 'canberra-gtk-module'
#     XDG_SEAT = 'seat0'
#     PWD = '/home/tim/Documents/projects/Test'
#     LOGNAME = 'timothyjimothy'
#     XDG_SESSION_TYPE = 'tty'
#     SYSTEMD_EXEC_PID = '307'
#     XAUTHORITY = '/home/tim/.Xauthority'
#     WINDOWPATH = '1'
#     MOTD_SHOWN = 'pam'
#     GTK2_RC_FILES = '/etc/gtk-2.0/gtkrc:/home/tim/.gtkrc-2.0:/home/tim/.config/gtkrc-2.0'
#     HOME = '/home/tim'
#     LANG = 'en_US.UTF-8'
#     XDG_CURRENT_DESKTOP = 'KDE'
#     KONSOLE_DBUS_SERVICE = ':1.106'
#     VIRTUAL_ENV = '/home/tim/Documents/projects/Test'
#     KONSOLE_DBUS_SESSION = '/Sessions/1'
#     PROFILEHOME = ''
#     INVOCATION_ID = '9f62fd2ba1044938904bdb1bd24ccfa8'
#     KONSOLE_VERSION = '211200'
#     KDE_SESSION_UID = '1002'
#     XDG_SESSION_CLASS = 'user'
#     PYTHONPATH = ': ~/.local/bin/python3.9: ~/.local/bin/python3.9'
#     TERM = 'xterm-256color'
#     USER = 'timothyjimothy'
#     COLORFGBG = '15;0'
#     KDE_SESSION_VERSION = '5'
#     DISPLAY = ':0'
#     SHLVL = '4'
#     XDG_VTNR = '1'
#     XDG_SESSION_ID = '1'
#     XDG_RUNTIME_DIR = '/run/user/1002'
#     PS1 = '(Test) [\\u@\\h \\W]\\$ '
#     QT_AUTO_SCREEN_SCALE_FACTOR = '0'
#     XCURSOR_THEME = 'Sweet-cursors'
#     XDG_DATA_DIRS = '/home/tim/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/'
#     KDE_FULL_SESSION = 'true'
#     PATH = '/home/tim/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/tim/Documents/projects/Test/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/tim/.local/bin/:/home/tim/.local/bin/'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1002/bus'
#     KDE_APPLICATIONS_AS_SCOPE = '1'
#     MAIL = '/var/spool/mail/timothyjimothy'
#     OLDPWD = '/usr'
#     KONSOLE_DBUS_WINDOW = '/Windows/1'
#     _ = '/home/tim/Documents/projects/Test/bin/buildozer'
#     PACKAGES_PATH = '/home/tim/.buildozer/android/packages'
#     ANDROIDSDK = '/home/tim/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/tim/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by RobertFlatt** [comment] 2022-01-04 05:29
Probably duplicate of https://github.com/kivy/python-for-android/issues/2265 and https://github.com/kivy/python-for-android/issues/2223

**Comment by misl6** [comment] 2022-04-06 20:07
Agree. Duplicated of #2265

**Closed by misl6** 2022-04-06 20:07 UTC

**Comment by Quinniboi10** [comment] 2022-12-11 19:07
Jesus stop sending me in circles I just want the answer to the question

**Comment by JayantSeth** [comment] 2023-05-15 04:45
Is this issue fixed, I am still facing this

**Comment by hinviarm** [comment] 2023-07-18 00:35
For android, we have recorderStartMicrophone on androidhelper
