### ISSUE TITLE
autoclass: Class only found when called in specific places?

### ISSUE THREAD

**Issue by cathay** [kivy/python-for-android#2242] opened 2020-06-24 23:11 UTC
### Versions

- Python: 3.8
- OS: Android 9
- Kivy: 1.11.1
- OpenJDK: 1.8

### Description
I tried to use ffprobe in my ```helper.py``` as:

```
def get_video_length(filename):
    ffprobe = autoclass('com.arthenica.mobileffmpeg.FFprobe')
    config = autoclass('com.arthenica.mobileffmpeg.Config')
    ....
```
We got the error `jnius.jnius.JavaException: Class not found b'com/arthenica/mobileffmpeg/FFprobe'`. The fix for it is put 
`ffprobe = autoclass('com.arthenica.mobileffmpeg.FFprobe')`  in `__init__.py` but it seems not straightforward to me. I would like to get some thoughts on it. 

**`get_video_length` was called on different thread from main thread**

### buildozer.spec
```
android.gradle_dependencies = com.arthenica:mobile-ffmpeg-full:4.3.2
```
ffmpeg repository: https://github.com/tanersener/mobile-ffmpeg

Command:
```
buildozer --verbose android debug deploy run
```

**Comment by Ham-Merhead** [comment] 2020-06-25 03:13
Hmm, interesting....

All the examples show autoclass calls that are global (and probably more to the point static)
So perhaps it matters when autoclass happens?
The usage shown here is local, moving it to `__init__.py` would make it global.

And while digging I found this, which may be also be interesting 
https://pyjnius.readthedocs.io/en/stable/api.html#pyjnius-and-threads

**Comment by praaggg** [comment] 2021-01-09 08:18
In my case the build itself fails while using below in spec file
android.gradle_dependencies = com.arthenica:mobile-ffmpeg-full:4.3.2

**Comment by dbnicholson** [comment] 2022-05-31 15:42
I think the issue is most likely that you're trying to resolve the class from a new native thread. See #2533 for details.

**Comment by Julian-O** [comment] 2023-11-20 00:51
@cathay Was this resolved by the comment above?

**Closed** 2024-01-01 05:01 UTC
Labels: awaiting-reply
