### ISSUE TITLE
pythonforandroid.toolchain.py: error: unrecognized arguments: --dir

### ISSUE THREAD

**Issue by cederom** [kivy/python-for-android#2775] opened 2023-04-13 11:54 UTC
I have reported that issue on Buildozer tracker, but it seems more related to pythonforandroid, so I just reference the issue here, all details inside :-)

https://github.com/kivy/buildozer/issues/1591

The problem exist for p4a.branch = master, develop, and v2023.02.10; and buildozer 1.5.0, 1.5.1-dev0.

**Comment by cederom** [comment] 2023-04-14 04:20
Okay so **this is a blocker**. I have tried on macOS 12 x86, macOS 13 M1, Linux Debian AMD64.. there is this `pythonforandroid.toolchain` problem on all platforms right before the apk packaging. Python 3.9.16. No matter what NDK / API I select. No matter if I use p4a release / master / develop.
* `buildozer android update` works.
* `buildozer android debug` fails.

Help! :-)

**Comment by misl6** [comment] 2023-04-14 16:13
Duplicate of https://github.com/kivy/buildozer/issues/1591

Thank you for reporting!

**Closed by misl6** 2023-04-14 16:13 UTC
