### ISSUE TITLE
Copy past is not working on kivy mobile app

### ISSUE THREAD

**Issue by navjotcis** [kivy/python-for-android#2270] opened 2020-07-29 12:52 UTC
I have been working on Kivy android application from last one year and I have asked about p4a copy past issue 
https://github.com/kivy/kivy/issues/6440

I have also checked recent commits of p4a and Kivy both but still facing this issue with p4a so can anybody let me know why this issue is not fixed from the last one year? 
please try to fix the issue because it is the major issue with mobile applications here user can not able to copy text field text.

**Comment by navjotcis** [comment] 2020-08-11 12:38
Does anyone have a solution for this?

**Comment by Julian-O** [comment] 2023-11-20 00:32
> can anybody let me know why this issue is not fixed from the last one year?

Yes. This is a project run by busy volunteers, who have over a thousand of other issues and ideas to investigate.

It is Open Source, so you can get in and fix the problems yourself, and share the result with others. Alternatively, you can hire/sponsor other people to look into your favourite issue.

Closing as a duplicate of the existing bug report.

**Closed by Julian-O** 2023-11-20 00:32 UTC
Labels: bug
