### ISSUE TITLE
Current android sdk has removed the ant/build.xml

### ISSUE THREAD

**Issue by kamathln** [kivy/python-for-android#1069] opened 2017-06-21 04:22 UTC
Please raise the priority of switching to gradle.
 
[Same issue at processing](https://github.com/processing/processing-android/issues/307)

```
/home/kamathln/.local/share/python-for-android/dists/kivycatalog/build.xml:21: Cannot find /opt/apps/android-sdk-linux/tools/ant/build.xml imported from /home/kamathln/.local/share/python-for-android/dists/kivycatalog/build.xml
```

**Comment by inclement** [comment] 2017-07-09 16:07
This should hopefully be fixed by https://github.com/kivy/python-for-android/pull/1071, but it needs people to test it.

**Comment by gobftald1** [comment] 2017-07-19 22:20
this is caused by the fact that Android team has decided to remove all old and obsolete scripts from SDK in march release of 25.3.0 SDK Tools

downloaded the previous version e.g. for OSX from
https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip

then replace the tool directory in the fresh android-ndk with this one

BTW it solves the problem with the missing/old "android" command in pythonforandroid/build.py

**Comment by kamathln** [comment] 2017-07-20 09:07
Thanks! Already using an older version of tools. But this can best be described as a "hack" and there is no guarantee how much longer it will keep working.

**Comment by gobftald1** [comment] 2017-07-20 13:01
you are right, this for the new users, like me, who downloaded this p4a toolchain only 2-3 weeks ago and install its SDK/NDK environment from scratch with their update version, then run into these problems immediately

sorry about this "hack", but I should have been made even more brutal "hacks", like [https://github.com/kivy/python-for-android/issues/1012](url)

but if I didn't want to loose my motivation for using this environment I should find quick fixes to continue my projects, even with these dirty solutions,

I can simple track these workarounds, so if there would be an updated toolchain I will able to check whether original problems would have been solved or I should use these hacks again

**Comment by inclement** [comment] 2017-09-30 23:16
https://github.com/kivy/python-for-android/pull/1071 is now merged, so gradle should work (and be used by default with newer SDK versions) in the master branch.

I wouldn't be surprised if there are still issues for some people, so testing this would be very helpful to accelerate its progression to the stable branch (and therefore buildozer users).

**Closed by inclement** 2017-09-30 23:16 UTC
