### ISSUE TITLE
After building FFMpeg recipe, I still am not able to do ffmpeg -v

### ISSUE THREAD

**Issue by wingchen** [kivy/python-for-android#1146] opened 2017-10-22 00:59 UTC
Hi,

I am very new to `python-for-android`, but I am loving it so far though.

I was able to build ffmpeg using the recipe with ubuntu 14.04 and the following dependencies list (some of them are created by myself):

```
requirements = python2,sqlite3,kivy,poyo,peewee,numpy,gevent,pyopenssl,requests,opencv,flask,websocket-client,ffmpeg,pyfcm
```

I was able to get the built *.so files.

<img width="404" alt="screen shot 2017-10-21 at 5 56 47 pm" src="https://user-images.githubusercontent.com/798321/31857093-53edec1c-b689-11e7-8683-c78412208dc5.png">

But when I try to run the following function in my main.py, I got permission error.

```
def test_ffmpeg():
  try:
    import subprocess
    print(subprocess.check_output(['ffmpeg', '-version']))
  except Exception as e:
    print(e)
    print('==> ffmpeg is not good :(, nooooooooooooo')
  else:
    print('==> ffmpeg is good :)')
```

Error: `I/python  (25293): [Errno 13] Permission denied`

Am I missing something? thanks

**Comment by germn** [comment] 2017-10-23 10:00
`ffmpeg` recipe is designed to be dependency for `ffpyplayer` recipe (`ffpyplayer` - uses as a video provider), not something to be used "as is".

When you call `subprocess.check_output(['ffmpeg', '-version'])` what you're trying to do is to run `ffmpeg` executable file, but subprocess doesn't know where is that file (file named `ffmpeg`) located and you get error. But `ffmpeg` binary doesn't exist anywhere - it wasn't build by recipe since recipe [isn't designed](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/ffmpeg/__init__.py#L92) to provide it. Recipe builds bunch of `.so` files instead that used by `ffpyplayer` module. These files can also be used [manually](https://helloacm.com/calling-c-shared-library-from-python-code-linux-version/), but it's whole another topic.

Can you tell what task you're going to solve with `ffmpeg`? May be this task can be solved with `ffpyplayer` module directly (see [it's api](http://matham.github.io/ffpyplayer/api.html)).

**Comment by wingchen** [comment] 2017-10-23 17:59
@germn I would like to run a couple of commands, something like:

```
ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 /path/to/file.mp4
```

or

```
ffmpeg -y -r 15 -i source.h264 -movflags +faststart -vcodec libx264 -profile:v baseline -level 3.0 -acodec aac destination.mp4
```

I am looking if I am able to do it in `ffpyplayer`. If you know how to do it, please let me know too.

Thanks a lot for the response.

**Comment by wingchen** [comment] 2017-10-24 00:47
I found that as soon as I put `ffmpeg` and `ffprobe` under `/system/lib(64)`, I am able to run the commands in shell. I am testing it from python `subprocess.check_output`.

**Comment by AndreMiras** [comment] 2019-01-31 19:48
Well binary compilation it's specifically in the recipe configure part, see https://github.com/kivy/python-for-android/blob/95d41f7/pythonforandroid/recipes/ffmpeg/__init__.py#L81 so you can just enable it right?

**Comment by inclement** [comment] 2019-01-31 19:49
Closing as not an issue, given how the ffmpeg recipe works.

**Closed by inclement** 2019-01-31 19:49 UTC

**Comment by AndreMiras** [comment] 2019-01-31 20:00
I can confirm I could generate the `ffmpeg` binary by commenting the flag mentioned above.
I compiled in Docker using the following:
```sh
python setup_testapp_python3.py apk --sdk-dir $ANDROID_SDK_HOME --ndk-dir $ANDROID_NDK_HOME --requirements python3,ffmpeg
```
And the binary got compiled see it here:
```sh
file /home/user/.local/share/python-for-android/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_21/ffmpeg/bin/ffmpeg
/home/user/.local/share/python-for-android/build/other_builds/ffmpeg/armeabi-v7a__ndk_target_21/ffmpeg/bin/ffmpeg: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
```

**Comment by rishabhjoshi** [comment] 2019-03-14 09:00
@AndreMiras 
I am also able to compile the binary, but I'm still unable to run/use them on Android device. 
I'm trying to load a mp4 using pydub, but it's giving me a Permission Denied [13] error as above.

**Comment by AndreMiras** [comment] 2019-03-14 16:18
You should debug that issue trying to `subprocess.check_output()` something that you knows is working on the file system e.g. the `ls` or `uname` command. Then if this works try to `ls -l` the `ffmpeg` binary also from your android app also using subprocess call. The idea is to see if 1. you have the correct path to it and 2. if it has the execution flag. Please share your debug session here

**Comment by adarsh1783** [comment] 2020-06-26 08:53
> I found that as soon as I put `ffmpeg` and `ffprobe` under `/system/lib(64)`, I am able to run the commands in shell. I am testing it from python `subprocess.check_output`.

@wingchen  Can you explain how did you genrated ffmpeg binary for android and where did you put ? If possible please provide code snippets too. Thanks
