### ISSUE TITLE
bind recipes to well defined versions

### ISSUE THREAD

**Issue by lufebe16** [kivy/python-for-android#1115] opened 2017-09-15 18:50 UTC
Several recipes use version = 'master'. This prevents from reproducible builds, as master is not a well defined package. 

`lb@lb7520 ~/.local/lib64/python3.4/site-packages/pythonforandroid/recipes/pyjnius $ grep -irn "version = [']master[']" .
./pygame_bootstrap_components/__init__.py:7:    version = 'master'
./pyjnius/__init__.py:9:	version = 'master'
./jedi/__init__.py:6:    # version = 'master'
./vispy/__init__.py:7:    version = 'master'
./cymunk/__init__.py:5:    version = 'master'
./ffpyplayer/__init__.py:10:    version = 'master'
./kivent_core/__init__.py:6:    version = 'master'
./pyzmq/__init__.py:13:    version = 'master'
./libmysqlclient/__init__.py:10:	version = 'master'
`
 It would be better to use the latest release versions instead.

**Comment by zwyuan** [comment] 2017-09-23 20:28
Second this issue.

**Comment by inclement** [comment] 2017-09-23 21:21
In most (if not all) of these cases, there's some reason not to use the latest stable release. However, it's a fair point, for most of them we should probably use specific git commits or create new releases as appropriate.

**Comment by KeyWeeUsr** [comment] 2017-09-23 22:13
Creating releases for some of them might make no sense at all IMO because for example Kivent modules can have separate fixes and if there was a bug in one of the, I doubt there would be a separate release for the whole Kivent (I might be wrong though).

Then there are packages which have never even had a release (smaller, from Kivy org mostly) so we would need to create some release process for them (hopefully even with tests and CI where applicable). The change to specific commits would make it faster for p4a builds to become more reproducible this way though.

**Comment by frmdstryr** [comment] 2017-10-24 23:07
Is there any reason p4a can't use something like [entry_points](https://stackoverflow.com/questions/774824/explain-python-entry-points#9615473) built into setuptools to allow version specific recipes to be installed independently of p4a? 

Using this, each recipe could be in it's own repo and you could install a specific version with pip.
```
pip install p4a-<recipe>==<version>
```

Adding this should just be an update to https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipe.py#L620 , to check for packages installed with a given entry point (for example a fancy `p4a-recipe`) entry point.

I can submit a PR if this is an acceptable solution.

P.S. An `entry_point` for custom bootstraps (ex `p4a-bootstrap`) could be used in the same way.

**Comment by inclement** [comment] 2019-01-30 23:13
Closing as not a priority for these specific recipes, but something that has been addressed in several cases where possible by sticking to a specific commit.

**Closed by inclement** 2019-01-30 23:13 UTC
