### ISSUE TITLE
p4a recipes crashes on matplotlib

### ISSUE THREAD

**Issue by jb1123** [kivy/python-for-android#895] opened 2016-10-03 16:30 UTC
I have installed p4a with 
$ pip install --upgrade python-for-android

Recipe matplotlib is not on github repository, but something is downloaded by pip, installed directory has no .py file perhaps that's why p4a recipes crashes. 

$ p4a recipes
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
android      None    
    depends: [('python2', 'python3'), ('python2', 'python3crystax'), ('pygame', 'sdl2', 'genericndkbuild')]

  File "/home/jb/python/venv/local/lib/python2.7/site-packages/pythonforandroid/recipe.py", line 623, in get_recipe
    raise IOError('Recipe does not exist: {}'.format(name))
IOError: Recipe does not exist: matplotlib
$

**Comment by inclement** [comment] 2016-10-03 20:07
Thanks for the report, but I'll close this as a duplicate of https://github.com/kivy/python-for-android/issues/865

I think this may arise from me packaging some extra folders when I bundled p4a for pip, so it should be fixed with the next release.

**Closed by inclement** 2016-10-03 20:07 UTC

**Comment by jb1123** [comment] 2016-10-04 19:47
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
When do you plan to have the next release? Is git clone and local installation a valid intermediate solution? 
BR, Jacek
 
Dnia Poniedzia³ek, 3 Pa¼dziernika 2016 22:08 Alexander Taylor <notifications@github.com> napisa³(a)

Thanks for the report, but I'll close this as a duplicate of #865
I think this may arise from me packaging some extra folders when I bundled p4a for pip, so it should be fixed with the next release.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kivy/python-for-android","title":"kivy/python-for-android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/kivy/python-for-android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@inclement in #895: Thanks for the report, but I'll close this as a duplicate of https://github.com/kivy/python-for-android/issues/865\r\n\r\nI think this may arise from me packaging some extra folders when I bundled p4a for pip, so it should be fixed with the next release."}],"action":{"name":"View 
Issue","url":"https://github.com/kivy/python-for-android/issues/895#issuecomment-251211823"}}}
// ]]>
