### ISSUE TITLE
How to completely remove installed app?

### ISSUE THREAD

**Issue by hottwaj** [kivy/python-for-android#953] opened 2016-12-08 10:18 UTC
I'd like to test what happens on first install of my app, but there seems to be some residual settings (kivy config?) files stored somewhere that aren't deleted when I uninstall the app, or when I "Clear app data" as per [this link](http://www.androidcentral.com/android-201-how-and-when-clear-app-cache-or-data) 

What steps do I need to follow to completely delete the app, all settings and all user data?

Thanks!

**Comment by KeyWeeUsr** [comment] 2016-12-08 12:00
With the latest version of p4a I experience no such thing.

* interpreter + kv: `data/data/your.app.name`
* java stuff + jni/C: `data/app/your.apk`

Maybe you've tried `App.user_data_dir`, which is a folder on `sdcard/your.app.name` or I think I saw it even in `sdcard/Android/your.app.name` and your app uses such config from user_data_dir?

**Comment by hottwaj** [comment] 2016-12-08 12:22
Thanks, I'll look into this further...  In case it makes a difference I'm still using the SDL/Pygame bootstrap.

**Comment by hottwaj** [comment] 2016-12-08 12:59
Aha just found it...
The file ".myapp.ini" (Kivy config file for my app) is stored in "Main Storage" i.e.
/storage/emulated/0/.myapp.ini

My app's [user_data_dir](https://kivy.org/docs/api-kivy.app.html#kivy.app.App.user_data_dir) folder is:
/storage/emulated/0/myapp

These don't get deleted if I uninstall my app.  Is this an issue with the pygame bootstrap?

**Comment by hottwaj** [comment] 2016-12-08 13:05
Probably something to do with [this change](https://github.com/kivy/python-for-android/commit/c36cf0df31a95f974a3ca2717451c0b186b7c90b) which I may not have pulled into my p4a repo...  Will verify later - sorry for the posting noise.

**Comment by KeyWeeUsr** [comment] 2016-12-08 15:20
No, this is purely Kivy thing and I didn't find anything from p4a to even target such file (that env. var is something different). I think it's just unhandeled behavior from the Kivy side, because the `Config` for some reason places the `.ini` outside of the app folder.

I'm not sure if it's desired, however the app contains the default `kivy.ini` file at the same folder where folder with logs is (`data/data/...`) and you probably should target that file if needed. It's still an issue so try to open one in Kivy repo or ask on IRC. If you'd target `kivy.ini` file and your app is both android and e.g. some desktop, your default desktop config will be most likely overwritten (`<user profile>/.kivy/config.ini`)

**Comment by hottwaj** [comment] 2016-12-10 11:50
Checked this with newest p4a and yes, config file and user_data_dr still reside in the same place and are not deleted with the app.  However I don't have the same issue on ios.  Can close if this should be moved to kivy repo?  Cheers

**Comment by KeyWeeUsr** [comment] 2016-12-10 11:56
Are you sure there are no leftovers in iOS somewhere in the system? About the `user_data_dir`, that folder isn't deleted anywhere afaik - desktops & android.

**Comment by hottwaj** [comment] 2016-12-11 17:16
I made the ios comment because if I delete my app and reinstall it it
behaves as if it has just been installed for the first time, which makes me
think that the config file for my app is getting deleted on uninstall.  I
haven't actually checked the file system.

Thanks

**Comment by KeyWeeUsr** [comment] 2016-12-12 22:11
@hottwaj Could you please post some minimal example that creates such a config file? I tested with latest kivy and p4a this one:

```
from kivy.base import runTouchApp
from kivy.uix.boxlayout import BoxLayout
from kivy.config import Config
Config.set('graphics', 'height', 50)
Config.write()
runTouchApp(BoxLayout())
```

But both on Windows and Android it either creates a new one or overwrites in:

* Windows -> `%appdata%/.kivy/config.ini`
* Android -> `/data/data/app.dir/app/.kivy/config.ini` or if sdl2 launcher `/sdcard/kivy/app/.kivy/config.ini`

If your code uses `Config.read()` or `Config.update_config()` it's most likely your fault by choosing a path that's not automatically deletable. Still I think I've seen this behavior before, but I'm not sure how to reproduce.

**Comment by hottwaj** [comment] 2016-12-14 11:16
Sure I will get this done, but probably not until next week - busy times! Cheers

**Comment by KeyWeeUsr** [comment] 2016-12-22 19:21
@hottwaj Please don't forget about this issue, it seems really useful for resolving the additional permission of casual kivy apps.

**Comment by hottwaj** [comment] 2016-12-22 23:04
Sure, I have it on my list.  I just looked through my config code and can't see anything obvious - I don't use Config.read of Config.update_config.

It will take me more time to build a simplified test I'm afraid.

In the meantime in case it's useful, I use the following config related functions, roughly in this order:
First I provide a build_config method for my app in which I use config.setdefaults.
Later I use config.getint, config.set and config.write during the build() method of my app (when the app runs for the first time)
I use app.load_config somewhere.
I also use ConfigParserProperty in a few places.

Sorry, probably not very helpful... will try to put a simple test together soon.  Thanks

**Comment by KeyWeeUsr** [comment] 2016-12-22 23:47
Probably it won't be needed anymore, the description was enough. It's the example from `App` docs. So yeah, a bug 🙍  thanks for the description.

    class TestApp(App):
        def build_config(self, config):
            config.setdefaults('section1', {
                'key1': 'value1',
                'key2': '42'
            })

        def build(self):
            config = self.config
            return Label(text='key1 is %s and key2 is %d' % (
                config.get('section1', 'key1'),
                config.getint('section1', 'key2')))

**Comment by hottwaj** [comment] 2016-12-23 17:48
Cool, glad that description was helpful!  Thanks

**Comment by llfkj** [comment] 2017-01-03 21:20
Uh oh. I currently rely on this (mis?)feature.  Can you give me some time to have a more detailed look and think of a solution that addresses both the described issue, and the way I'm currently using it?

**Comment by KeyWeeUsr** [comment] 2017-01-03 21:28
@llfkj here, I zoomed it for you 🐼 [bad line](https://github.com/kivy/kivy/blob/5913d861f45119dfff0b6cb5d004e6f79858563c/kivy/app.py#L657). This is why the config is thrown to sdcard like if it is a root folder. It could be fixed with targeting directly [external storage directory](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory()), which I guess is removed after uninstalling the app (or removing its data, testing welcome).

More about it [here](https://mbcdev.com/2013/04/13/using-androids-external-storage-effectively-and-judiciously/). According to that quote it's removed, yet I experienced weird stuff on Gingerbread like 2 years ago, so...:

> The SDK provides us with handy methods to determine where to put our stuff.  These places will be deleted automatically when a user removes our apps and this keeps things tidy.

**Comment by inclement** [comment] 2019-01-31 00:14
Closing as a Kivy issue rather than a p4a one, which we're aware of and working to fix.

**Closed by inclement** 2019-01-31 00:14 UTC

**Comment by JonasT** [comment] 2019-01-31 00:15
@inclement just for what it's worth, pretty sure it's already fixed on kivy master with the recent config & user data location change on android. (I pushed for that one because of the SDL2 upgrade that introduced the permission stuff that needs it) :+1:
