### ISSUE TITLE
env must be a dict

### ISSUE THREAD

**Issue by bitinerant** [kivy/python-for-android#2170] opened 2020-05-04 18:15 UTC
### Versions

* Python: 3.8.2
* OS: Ubuntu 20.04

### Description

My `buildozer android release` command failed with `env must be a dict`, exactly as described in [Askubuntu #1233200](https://askubuntu.com/questions/1233200/) and the [answer proposed by Camden Senneff](https://askubuntu.com/a/1233673/705492) worked well for Likes_to_Program123 **and** for me.

This seems similar to [bug #1080](https://github.com/kivy/buildozer/issues/1080) but the diff is different.

Here is the diff that fixed the issue for me:
```
kivy@kivy-buildozer:~/bitburrow/.buildozer/android/platform/python-for-android$ git diff
diff --git a/pythonforandroid/build.py b/pythonforandroid/build.py
index 8f0ac40a..3642337a 100644
--- a/pythonforandroid/build.py
+++ b/pythonforandroid/build.py
@@ -788,13 +788,13 @@ def run_pymodules_install(ctx, modules, project_dir=None,
         info('Upgrade pip to latest version')
         shprint(sh.bash, '-c', (
             "source venv/bin/activate && pip install -U pip"
-        ), _env=copy.copy(base_env))
+        ), _env=dict(copy.copy(base_env)))
 
         # Install Cython in case modules need it to build:
         info('Install Cython in case one of the modules needs it to build')
         shprint(sh.bash, '-c', (
             "venv/bin/pip install Cython"
-        ), _env=copy.copy(base_env))
+        ), _env=dict(copy.copy(base_env)))
 
         # Get environment variables for build (with CC/compiler set):
         standard_recipe = CythonRecipe()
@@ -838,7 +838,7 @@ def run_pymodules_install(ctx, modules, project_dir=None,
                 "venv/bin/pip " +
                 "install -v --target '{0}' --no-deps -r requirements.txt"
             ).format(ctx.get_site_packages_dir().replace("'", "'\"'\"'")),
-                    _env=copy.copy(env))
+                    _env=dict(copy.copy(base_env)))
 
         # Afterwards, run setup.py if present:
         if project_dir is not None and (
```

**Comment by AndreMiras** [comment] 2020-05-04 18:22
Could you please run on `p4a.branch = develop` and share your entire build log?

**Comment by bitinerant** [comment] 2020-05-04 19:32
With `p4a.branch = develop`, I get a different error. The full log is [pastebin 4ATGR3Pz](https://pastebin.com/4ATGR3Pz).

With `p4a.branch = master`, I get the `env must be a dict` as described above. The full log is [pastebin ydFenLLf](https://pastebin.com/ydFenLLf)

**Comment by AndreMiras** [comment] 2020-05-04 19:40
So yes this issue is indeed fixed on the develop branch and not in master because we haven't made a release yet.
Regarding the error you get in develop, it seems like a different story (one of theses may need need a recipe: ansible, certifi, jinja2)

**Comment by Ham-Merhead** [comment] 2020-05-09 01:29
@AndreMiras 
This second error (Invalid special arguments) started appearing to users just over a week ago:
https://groups.google.com/forum/#!searchin/kivy-users/Invalid$20special$20arguments%7Csort:date

Here is one example, the log shows it only depends on certifi
https://groups.google.com/forum/#!msg/kivy-users/_Ku_2vIxSGk/QWK98UDGBAAJ

Certifi appears to be pure Python (plus a data file), and appears to be a (new?) dependency of one of the default packages.

**Comment by thica** [comment] 2020-06-28 15:03
Hi , I can confirm the error. The solution is posted:
https://askubuntu.com/questions/1233200/buildozer-crashed-with-env-env-must-be-a-dict

**Closed** 2023-11-20 01:01 UTC
