### ISSUE TITLE
Can't type anything into textinput using new toolchain

### ISSUE THREAD

**Issue by Fogapod** [kivy/python-for-android#1102] opened 2017-08-29 12:19 UTC
### Versions
* kivy: master
* buildozer: 0.34dev ([buildozer.spec](https://gist.github.com/Fogapod/97b42651d23ae6c97274d312e20cca81)) `buildozer android debug`
* p4a: master

### Description
`TextInput` does not allow any symbols to be entered (except clipboard)
The problem exists on several devices. On the others there are not any problems.
I think, it can be referenced to https://github.com/kivy/kivy/issues/5043, but not sure where the problem is: in kivy or in python-for-android.
Problem does not appear in old toolchain

#### Devices with problem confirmed (using stock keyboard only): 
* Samsung J3 (6), android 5.1.1

### Code
Even app returning a single `TextInput` won't work.

**Comment by inclement** [comment] 2017-08-29 12:24
Would you be able to download and run the apk at http://inclem.net/files/Kivykeyboardtester-0.5-debug.apk ? If you could follow the instructions, it will end with emailing me some information about what keyboard events kivy is receiving. I never got the app ready to publish publicly, but I think it should work for this.

**Comment by Fogapod** [comment] 2017-08-29 12:47
@inclement [keyboard_log.txt](https://gist.github.com/Fogapod/5264fb01e56ebea297143e1c7d5e6a00)

**Comment by inclement** [comment] 2017-08-29 13:03
Fantastic, that's extremely useful, thanks!
The problem seems to be that Kivy doesn't currently do anything with sdl2 textediting events, instead assuming that text entry occurs only via individual key events, or textinput events. I had guessed this before, but wasn't able to reproduce the problem on any devices. Your log confirms it, and should hopefully be enough to code an initial solution to the problem, although I'm not sure if some parts of it could be tricky.

**Comment by inclement** [comment] 2017-11-29 23:22
Aritodo reported that this happens with the minuum keyboard.

**Comment by inclement** [comment] 2018-01-30 22:12
@khertan reports:

> TextInput display text only when suggestion validate with enter or space on Asus ZenPhone3. even with keyboard_suggestions: False.

**Comment by vanphong1310** [comment] 2018-03-13 02:15
I have same problem like @khertan. I try installing @inclement's app but it always crash and close at first test (I only can type 'One two three' then it crash).
And the strange thing, I can nomarlly type in Kivy showcase app, it work very well.

My phone: Samsung Galaxy A9 Pro with Android 7.0
My keyboard: Laban Key Go Tieng Viet
I built my app with buildozer 0.34, kivy 1.10.0, cython 0.25.

**Comment by khertan** [comment] 2018-03-20 08:15
The problem is really the ZenUI Keyboard on Asus, switching to google keyboard i didn't have that problem

**Comment by vanphong1310** [comment] 2018-03-22 05:21
I try building my app with android_old command (that use pygame instead of SDL) then I can type everything I want  :smiley:.
Seems like the problem is of SDL, it don't work well with some keyboard IME - In Linux, I need update SDL to version 2.0.5 for typing with Fcitx.

**Comment by inclement** [comment] 2019-01-30 23:15
This may have been improved by the move to sdl2.0.9.

**Comment by inclement** [comment] 2019-02-01 11:34
I'm going to provisionally close this because it seems there's a good chance it's been fixed by SDL2.0.9. We know of various bugs that have been fixed, and @vanphong1310's observation of improvements on Linux is also a good sign.

This can be reopened if the issue still occurs, please feel free to comment if that's the case.

**Closed by inclement** 2019-02-01 11:34 UTC

**Comment by vanphong1310** [comment] 2019-03-01 14:44
I have just tried to build again with sdl2 2.0.9.<br>
Now, I can enter text but only in English, IME does not work so I cannot enter Vietnamese text.<br>
I tried with Gboard keyboard, Samsung's stock keyboard, only English work though I switched to Vietnamese.
