### ISSUE TITLE
Existing distribution not detected due to pip package casing mismatch

### ISSUE THREAD

**Issue by pakal** [kivy/python-for-android#2494] opened 2021-09-25 14:26 UTC
P4a kept rebuilding the entire android distribution for my project when i did "buildozer android deploy", I tracked down the bug to a simple case sensitivity mismatch here: 
https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/distribution.py#L119

I had "Pillow" in my buildozer.spec dependencies, wherease the list stored in dist_info.json was lowercased:

`[INFO]:    >>>> custom logging >>>> recipe mismatch: Pillow not in ['freetype', 'hostpython3', 'jpeg', 'libffi', 'openssl', 'png', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'pytz', 'setuptools', 'decorator', 'pillow', 'pycparser', 'six', 'cffi', 'pyjnius', 'android', 'kivy', 'pycryptodome', 'uuid0', 'kivymd', 'docutils', 'plyer', 'certifi', 'pymongo', 'multitimer', 'psutil']`

Maybe P4a should do case insensitive comparison here? 
And maybe have some DEBUG logging to explain why an existing distribution is dismissed?

**Comment by Julian-O** [comment] 2023-11-20 03:02
Marking as duplicate of #2062

**Closed by Julian-O** 2023-11-20 03:02 UTC
Labels: bug, Priority: Low
