### ISSUE TITLE
Download failed ( Downloading sqlite3 from https://www.sqlite.org/2021/sqlite-amalgamation-3350500.zip ) during buildozer -v andriod debug

### ISSUE THREAD

**Issue by Anikesh-kumar** [kivy/python-for-android#2881] opened 2023-08-20 09:03 UTC
[DEBUG]:   -> running mkdir -p /root/kivy/kivy_venv/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/packages/sqlite3
[INFO]:    -> directory context /root/kivy/kivy_venv/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/packages/sqlite3
[DEBUG]:   -> running basename https://www.sqlite.org/2021/sqlite-amalgamation-3350500.zip
[DEBUG]:        sqlite-amalgamation-3350500.zip
[DEBUG]:   Downloading sqlite3 from https://www.sqlite.org/2021/sqlite-amalgamation-3350500.zip
[DEBUG]:   -> running rm -f .mark-sqlite-amalgamation-3350500.zip
[INFO]:    Downloading sqlite3 from https://www.sqlite.org/2021/sqlite-amalgamation-3350500.zip

Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 482, in build_recipes
    recipe.download_if_necessary()
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 348, in download_if_necessary
    self.download()
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 398, in download
    self.download_file(self.versioned_url, filename)
  File "/root/kivy/kivy_venv/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 202, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
Download failed: <urlopen error [Errno 101] Network is unreachable>; retrying in 1 second(s)...Download failed: <urlopen error [Errno 101] Network is unreachable>; retrying in 2 second(s)...Download failed: <urlopen error [Errno 101] Network is unreachable>; retrying in 4 second(s)...Download failed: <urlopen error [Errno 101] Network is unreachable>; retrying in 8 second(s)...# Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=pingpong_1', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/root/kivy/kivy_venv/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     WSL2_GUI_APPS_ENABLED = '1'
#     WSL_DISTRO_NAME = 'Ubuntu'
#     NAME = 'Enigma'
#     PWD = '/root/kivy/kivy_venv'
#     LOGNAME = 'root'
#     HOME = '/root'
#     LANG = 'C.UTF-8'
#     WSL_INTEROP = '/run/WSL/15924_interop'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     WAYLAND_DISPLAY = 'wayland-0'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'root'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     XDG_RUNTIME_DIR = '/run/user/0/'
#     WSLENV = 'ELECTRON_RUN_AS_NODE/w:'
#     XDG_DATA_DIRS = '/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = ('/root/.buildozer/android/platform/apache-ant
 'Kumar/AppData/Roaming/npm:/snap/bin:/root/.local/bin/:/root/.local/bin/')
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/0/bus'
#     HOSTTYPE = 'x86_64'
#     PULSE_SERVER = 'unix:/mnt/wslg/PulseServer'
#     OLDPWD = '/root/kivy'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/root/.buildozer/android/packages'
#     ANDROIDSDK = '/root/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/root/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

Please check once
Thank You!!

**Comment by kuzeyron** [comment] 2023-08-21 13:39
This is a support question. You can find us on [Kivy@Discord](https://chat.kivy.org/)

**Comment by misl6** [comment] 2023-08-22 07:43
The issue is not reproducible anymore, this is likely a temporary failure on sqlite servers or a connection issue on your side.

Closing as support.

**Closed** 2023-08-22 07:43 UTC
Labels: support

**Comment by private1ne** [comment] 2024-02-17 08:20
In India Its not working try Connecting VPN

**Comment by wgy981930674** [comment] 2025-02-27 08:49
i can help you!先手动下载 sqlite-amalgamation-3350500.zip，然后上传.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/packages/sqlite3。新建一个空文件命名 .mark-sqlite-amalgamation-3350500.zip 即可解决！
